### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by whitewolfxs** [Greymerk/minecraft-roguelike#102]
I was wondering if you could maybe do an updated video on both changing a dungeon's theme and loot, since i have very little programming knowledge tho i would like to do a very custom server and it gets a bit confusing, if you have the time ofcourse but im sure more would also like this updated video.
I will wait for your reply and thanks for your time ! :)

**Comment by Greymerk** [comment]
I've been considering it. I'm also updating the wiki and will be adding examples there.

I'm right in the middle of rewriting and testing parts of the system, so will most likely be after that's further along.

**Comment by whitewolfxs** [comment]
also have two other question but not related to the video, one being can weight be added to dungeon spawn? so that some dungeons are rarer than others and is the 1.7.10 version using the most recent settings?

**Comment by Greymerk** [comment]
> weight be added to dungeon spawn?

yes, in the criteria
https://github.com/Greymerk/minecraft-roguelike/wiki/Criteria

1.7.10 is deprecated as far as i'm concerned. I'm no longer adding features to it. If a gamebreaking bug is found I will probably drag the branch out of mothballs to put a bandaid on something, but that's as far as i'm willing to support it. I haven't updated the 1.7 maintenance branch in 9 months.

**Comment by CriticalMole** [comment]
could you at the very least provide a zip of the files to go into the settings folder that is kept upto date...
I took the files in the zip back in 1.4'ish and when those are in the settings folder no loot generates in chests.
Thank you in advance
