### ISSUE TITLE
Using /roguelike settings reload

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#103]
When I use /roguelike settings reload, it says that there's no errors but I'm not getting any loot.
I'm using 1.10.2-1.5.7.

**Comment by Greymerk** [comment]
what sort of settings are you using?

**Comment by Alan19** [comment]
Dungeon Rooms and Mobs and Loot for B1-B2: [https://paste.ee/p/bIDw7](url)
B3-B5:[https://paste.ee/p/TDGZ0](url)

**Comment by Greymerk** [comment]
Hard to say without the required mods. Can you tell me what mods i'd need to test these?

**Comment by Alan19** [comment]
I think you would need 

- Abyssalcraft
- EnderZoo
- CyberWare
- PrimalCore
- Tinkers' Construct
- Dungeon Tactics
- TAIGA
- Natura
- Reliquary
- HarvestCraft
- Ars Magica 2
- Chisel
- Base Metals
- Forestry
- More Bees
- Botania
- Nature's Compass
- Immersive Engineering
- Extra Utilities 2
- Rockhounding: Ore Tiers
- FuturePack
- The One Probe
- Esteemed Innovation
- Evilcraft
- Actually Additions
- Quark
- Blood Magic
- Waystones
- Roots
- Giacomo's Fishing Net
I might have missed some and it would probably be easier if I did a binary search by removing the files

**Comment by Greymerk** [comment]
Thanks, i'll give it a try.

**Comment by Alan19** [comment]
I forgot to mention Railcraft and Embers

**Comment by Alan19** [comment]
While editing the json files, I made a mistake and it was caught by /roguelike settings reload and printed out what was wrong. However, after spawn a new dungeon, there was still no loot.

**Comment by Alan19** [comment]
I'll try updating to 1.5.8 and see if that fixes anything

**Comment by Alan19** [comment]
It's still occurring on 1.5.8 and everything but the loot is being inherited.

**Comment by Alan19** [comment]
The default loot still works though

**Comment by Greymerk** [comment]
I did some small tests with loot overrides, and I'm convinced now there's a bug with how this behaves.

I'm not sure what's causing it. will need to do more testing. It may be there's nothing actually wrong with your settings.

**Comment by Greymerk** [comment]
I think i figured this out. Will post a build in a bit and you can try it.

**Comment by Greymerk** [comment]
Try this one out. You'll need to explicitly add "builtin:base" to your inherit list now. It's to make that change in order for inheritance/overrides to function in a sane way.

https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.6.5.1

**Comment by Greymerk** [comment]
It's still not right.

I'm thinking I'll need to change how overrides work to be something like this:

```
{
	"name" : "main",
	"criteria" : {},
	"exclusive" : true,
	"inherit" : [
		{
			"id" : "builtin:base",
			"override" : ["LOOTRULES"]
		},
		"loot",
		"rooms"
	]	
}
```
You'd specify filters for things you don't want to inherit from the settings you include. It'd be much easier to understand.

I'll work on implementing it and see how it works.

**Comment by Greymerk** [comment]
I've given this some more thought and realized that it's probably not worth having the override system. It's too complicated to implement and to use. Rather it'd be much simpler to provide a clearer way to build up settings from smaller parts using inheritance. You could just leave out the loot settings.

That's what i'm trying to do now.

**Comment by Greymerk** [comment]
I worked it out, and did some playing with it, it's much easier to work with, and easier to understand. Will post a build of this sometime this afternoon hopefully.

**Comment by Greymerk** [comment]
Your loot system appears to work as expected now. I just have a couple other things that need to be addressed

I'd like the system to report when a block is unavailable, if possible.

**Comment by Greymerk** [comment]
this one should work:
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.6.5.2

But you'll need to add a new file to your inheritance chain:

default:base
```
{
	"name" : "base",
	"inherit" : [
		"builtin:secrets",
		"builtin:theme",
		"builtin:generator",
		"builtin:size",
		"builtin:segments"
	]
}
```

and remove the overrides.

**Comment by Alan19** [comment]
It's working now. Thanks!

**Comment by Greymerk** [comment]
Cool. I'll post the update to curse sometime this weekend probably.

**Comment by resinate** [comment]
alan are u able to make ur stuff naturally generate cuz my stuff isnt. all i did was custom block changes
