### ISSUE TITLE
custom spawners not working?

### ISSUE THREAD

**Issue by resinate** [Greymerk/minecraft-roguelike#104]
"spawners" : {
				"SPIDER" : [
					{"name" : "WitherSkull", "equip":true}
				],
				"ZOMBIE" : [
					{"name" : "WitherSkull", "equip":true}
				],
				"SKELETON" : [
					{"name" : "WitherSkull", "equip":true}
				],
				"BLAZE" : [
					{"name" : "WitherBoss"}
				]
			},

i see spawners with the mobs in them but they dont spawn
here is console error i got
[20:48:37] [Server thread/WARN]: Tried to add entity WitherSkull but it was marked as removed already

**Comment by Greymerk** [comment]
Are you trying to make spawners that fire witherboss skull projectiles?

**Comment by resinate** [comment]
yea was just gonna use defualt minecraft witherboss in place of blaze spawners. i can see the withers spining in the spawner and the effects of them spawning but thats it. and was trying to change other spawners to wither skeletons, just relized they didnt change name of them until 1.11 version. im currently using 1.10.2 for my pack.

if u have steam or curse where i can help test things ill be more than willing to help. my pack relies on ur mod soo much lol

**Comment by resinate** [comment]
more on spawning i can spawn any mob in the game except for wither boss itself for some reason.

**Comment by Greymerk** [comment]
> just relized they didnt change name of them until 1.11 version.

Welcome to my life.

> more on spawning i can spawn any mob in the game except for wither boss itself for some reason.

I've never tried this myself. I suspect they have an unusual spawning condition. Will look into it.

**Comment by resinate** [comment]
nah u can use /summon WitherBoss in game and it works. but yea if u can post the 1.5.8.2 on curse i would be soo happy lol what u have right now works really good

**Comment by Greymerk** [comment]
I did this, and it worked, at least in 1.11.2

wither bosses everywhere

```
{
	"name" : "wither",
	"criteria" : {},
	"tower" : {
		"type" : "ROGUE",
		"theme" : {
			"base" : "BLING"
		}
	},
	"levels" : {
		"all" : {
			"spawners" : {
				"SPIDER" : [
					{"name" : "wither"}
				],
				"ZOMBIE" : [
					{"name" : "wither"}
				],
				"SKELETON" : [
					{"name" : "wither"}
				],
				"BLAZE" : [
					{"name" : "wither"}
				]
			}
		}
	}
}

```

**Comment by Greymerk** [comment]
> if u can post the 1.5.8.2 on curse i would be soo happy lol what u have right now works really good

It's getting there. My hope is to complete more documentation and examples in the wiki, and also to put together automated tests which establish that these documented features are in fact working as expected. It's frustrating to do things and wind up with something unexpected happening.

**Comment by resinate** [comment]
theyre not letting me post the pack cuz of the update cuz its not on curse

**Comment by resinate** [comment]
btw {"name" : "wither"} is for 1.11 im using 1.10.2 lol
