### ISSUE TITLE
Request:  Reset dugeon

### ISSUE THREAD

**Issue by argrithmag** [Greymerk/minecraft-roguelike#107]
I have this on a private server for my kids.  It's a great mod!  Is there anyway to "reset" a dungeon after it's been generated?  Maybe through a command switch?

Thanks

**Comment by resinate** [comment]
nah but more always gen, if its at default of 10, ull find them outside every town. there not far apart

**Comment by Greymerk** [comment]
Similar to most other things in minecraft, the only way to reset it is to delete the chunks and allow them repopulate naturally. Other than that, no.

**Comment by resinate** [comment]
hey greymerk can u update the mod on curse? im getting rejected cuz theyre saying ur mod fix u made isnt allowed unless its posted on curse. i dunno how to pm you
