### ISSUE TITLE
Structure generation replacing End Portal Frames.

### ISSUE THREAD

**Issue by ghost** [Greymerk/minecraft-roguelike#111]
I don't know if it's intended or its a bug, but the structure generator ignores some important blocks. It wouldn't matter if it were some village or another structure type, but this is a really game-breaking feature.

**What happpens**:
End portal frames replaced by Roguelike Dungeon generator

**What should happen**:
The generator should run before vanilla minecraft structure generator or, if it's really have to run after, it needs to see when replace or not the vanilla generation blocks or structures

**How to reproduce**:
1. Create new world
2. Set Generate Structures: ON
3. Allows Cheats: Yes
4. Gamemode: Creative
5. Seed: -8913466909937400889
6. In the world, execute this: /tp @p 438 24 1721
7. See how end portal frames gets replaced by some other blocks.

Note: This happens even if you select World Type Large Biomes. In Amplified at that specific location does not happen.

**Comment by Greymerk** [comment]
it may even be wise to check the distance to the nearest stronghold spawn point while filtering potential dungeon locations. I believe that's a thing I can do, which will avoid the whole situation while allowing vanilla strongholds to remain untouched.

**Comment by Greymerk** [comment]
added this proximity check.

![2017-03-24_10 09 13](https://cloud.githubusercontent.com/assets/4789166/24305615/dbe17fcc-107a-11e7-99cb-0989de8b1a4f.png)
