### ISSUE TITLE
Random=True produces empty chests

### ISSUE THREAD

**Issue by Syndaryl** [Greymerk/minecraft-roguelike#112]
Minecraft 1.11.2
Forge 13.20.0.2259
Roguelike 1.6.6

When I set up roguelike.cfg to have
generous=true
and
random=true

All the dungeon chests are empty - hallway chests, and setpiece chests like the spider rooms, the bedroom, and the blacksmith room.

I'm enjoying the nonsensical variety in random=true mode as a change of pace but considering how difficult some of the dungeons end up (low Y level rooms on high Y level floors) it's a little off putting to have the treasure chests empty.

As a side note, so far all the random dungeons I've run into have the inside theme using clay bricks for walls, floors, and ceilings - regardless of what the tower was built out of and what theme it had. I've only checked a few dungeons out so my sample size is a lot smaller than with the chests (50+ chests, I think only four dungeons so far).

**Comment by Syndaryl** [comment]
Never mind, I see you fixed this seven days ago!

**Comment by Greymerk** [comment]
Yeah, i made a mistake while implementing the random dungeons, forgot to add loot.
