### ISSUE TITLE
MC1.11.2 Cascading WorldGen Lag

### ISSUE THREAD

**Issue by sandalle** [Greymerk/minecraft-roguelike#116]
In Minecraft 1.11.2 with Forge, I see these errors in the log
`[12:13:37] [Server thread/WARN] [FML]: Roguelike Dungeons loaded a new chunk (0, 43  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`

mezz fixed a similar issue in Actually Additions with https://github.com/Ellpeck/ActuallyAdditions/issues/690 , if that helps.

Mods:
* forge-1.11.2-13.20.0.2284
* Roguelike Dungeons 1.11.2-1.6.6

**Comment by Boodaflow** [comment]
I just submitted several other bug reports from different mods including Embers, Inventory Pets, AbyssalCraft, Recurrent Complex, Astral Sorcery, denseores, and Roguelike Dungeons with this same log spam.

    forge-1.11.2-13.20.0.2282
    Roguelike Dungeons 1.11.2-1.6.6

[15:11:16] [Server thread/WARN]: Roguelike Dungeons loaded a new chunk (10, 13  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by Boodaflow** [comment]
capnkirok of Inventory-Pets seems to have the solution as well:

https://github.com/capnkirok/Inventory-Pets/issues/170
