### ISSUE TITLE
Turning off normal dungeon spawning?

### ISSUE THREAD

**Issue by Winddbourne** [Greymerk/minecraft-roguelike#118]
I honestly really would like to stop vanilla minecraft dungeons from appearing in my worlds if I can. I'm adding a better dungeon mod because they are too easy to "defeat" and not fun at all. Could we please get a configuration setting that would stop them from generating?

**Comment by Greymerk** [comment]
You can already do this, even in vanilla minecraft, by switching off dungeons in customized world type.
