### ISSUE TITLE
Disable nether floor

### ISSUE THREAD

**Issue by ptk2003** [Greymerk/minecraft-roguelike#119]
There are any way to disable level 4 (nether style) generating in all tower type/biome?
I only found http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290238-roguelike-dungeons?comment=1067 - [ "depth": 3 ] - but don't know work it or not and which object use this.

**Comment by Alan19** [comment]
You can try making a custom dungeon and not include the last floor
