### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by Sunconure11** [Greymerk/minecraft-roguelike#126]
"[02:16:40] [Server thread/WARN]: Roguelike Dungeons loaded a new chunk (-10, 16  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config."

Not that frequent, but I'd advise looking into it. Found on the build for 1.11.2.

**Comment by Greymerk** [comment]
I can't think of a solution to this problem that doesn't create more problems than it solves. I think minecraft/forge should only provide undecorated chunks when this happens, which would solve the problem of runaway cascading worldgen.

At any rate, for the time being I'm not going to fix this.

**Comment by UnknownEvil** [comment]
Never?
