### ISSUE TITLE
Server Statup crash while Generating terrain. [1.12]

### ISSUE THREAD

**Issue by Fundryi** [Greymerk/minecraft-roguelike#127]
https://gist.github.com/NoplixDE/904a2c913d06c0d521b144869ba48f6c

**Comment by FiveEYZ** [comment]
Geting this crash on:
-  RoguelikeDungeons-1.12-1.7.0
-  forge-1.12-14.21.1.2426-universal

Here is a working link:
https://gist.github.com/FiveEYZ/9321b97429a218f90eff8847a824f98c

**Comment by Fundryi** [comment]
Thanks for updating it, idk why it got deleted :)

**Comment by Greymerk** [comment]
Odd.. doesn't seem to be an issue with the regular client. It looks as if this crash is being caused by a change to a method name that happened in forge at some point.
