### ISSUE TITLE
Frequency config option irritating

### ISSUE THREAD

**Issue by simonmeusel** [Greymerk/minecraft-roguelike#129]
The smaller the frequency config option is, the more dungeons it generates. This is irritating since normally the frequency should generate more dungeons the higher the number is. So either some more comments would be necessary or renaming the options to spawnRarity or something similar.

**Comment by Greymerk** [comment]
I've added another config option called "spawn chance" which is a probability value from 0 to 1. This will be a way adjust spawn rates using a percentage value.

at frequency 10, every village location has a dungeon. with a chance of 0.8 only 80% of village locations will have a dungeon.

**Comment by simonmeusel** [comment]
Thanks!
