### ISSUE TITLE
Any plan on releasing default settings as .json?

### ISSUE THREAD

**Issue by Insane96** [Greymerk/minecraft-roguelike#133]
So people will be able to edit default ones much easier

**Comment by Greymerk** [comment]
I have been considering setting up a repo with a comprehensive set of demo settings which approximates the defaults, and tests all the features of the system. It wouldn't be possible to exactly replicate the built-in settings (the loot specifically) because it's procedural in nature.

I'll try to set aside some time to put it together, since you brought it up.

**Comment by AtticusCrandorf** [comment]
This would be awesome! I've spent the last 4 hours trying override the default settings

**Comment by Insane-96** [comment]
Same, I've spent and entire day trying to override default loot, but what I came up with are empty "end dungeons" or empty chests

**Comment by Greymerk** [comment]
I wound up going down the rabbit-hole with a pretty major revamp to the settings json format. There's a few important things I have been meaning to change for a while.

basically after these changes the format will be more consistent and hopefully easier to understand.

**Comment by Insane-96** [comment]
And don't forget to add support for loot tables #114 😛

**Comment by Greymerk** [comment]
I should be able to add support for loot tables. It's not as easy as it aught to be because for some strange reason the loot tables are tightly coupled to the world object. Mojang doesn't seem to believe in separation of concerns.

**Comment by Greymerk** [comment]
I've been adding in a bunch of custom loot providers which you can assign using the json settings. You'll be able to do things like add pantaloons to the starter chest with {"type" : "specialty", "quality" : "wood", "equipment" : "legs"} (wood is just a generic quality level for all equipment, which for gear means leather)

when these custom item providers are invoked they'll automatically generate procedurally randomized gear as the mod does internally.

So far i've implemented json providers for potions, mixtures, tools, weapons, and armour. Eventually I should be able to fairly closely replicate the whole loot system in json.

Hopefully then you'll easily be able to mix them with loot tables, when i get those working.

**Comment by Greymerk** [comment]
The way I finally decided to support loot tables is much like they were intended to be used. By applying tables to chests themselves. You'll be able to target chests by type/level and set the loot table, but also add items using my loot system. The loot is specified in a list like this:

```
	"loot_tables" : [
		{"level" : [0, 1, 2], "table" : "minecraft:chests/simple_dungeon"},
		{"type" : "STARTER", "table" : "minecraft:chests/spawn_bonus_chest"},
		{"level" : 3, "table" : "minecraft:chests/jungle_temple"},
		{"level" : 4, "table" : "minecraft:chests/nether_bridge"}
	]
```

**Comment by Insane-96** [comment]
That's awesome! So you can specify loot tables but spawn other custom items too?

You'll release documentation to override default loot when the new version will be out? And the update will be for 1.11 too or 1.12 only?

**Comment by Greymerk** [comment]
Yes, you can both assign a loot table to a chest, as well as add items to it separately. It's nice that the system works that way.

For the time being I'm going to release it first on 1.12.2. any potential back-ports will come later. I should be ready to post a pre-release soon, but I need to do more testing on it to make sure everything's working as expected.

**Comment by Greymerk** [comment]
Here's the repo where the settings demo will be. So far I have a working demo of the basic dungeon.

[https://github.com/Greymerk/rd-settings](https://github.com/Greymerk/rd-settings)

**Comment by Greymerk** [comment]
Everything is implemented and nearly ready for testing. I'll probably post a pre-release build soon. There's a lot of cool new stuff, new capabilities. Some things are also way easier to do through json settings now.

The Spawner settings in particular have been greatly improved.

**Comment by Greymerk** [comment]
I've posted the update.

**Comment by Insane-96** [comment]
Testing it now

**Comment by Insane-96** [comment]
After a brief demo test seems that everything works properly. I'll now start making settings for my modpack and if any problem I'll report here

**Comment by Greymerk** [comment]
> Will mods like Resource loader work?

All my mod does is write a loot table to the nbt data for the chest. whatever happens after that is out of my hands. I assume the answer is probably yes.

**Comment by Greymerk** [comment]
>I'll now start making settings for my modpack and if any problem I'll report here

What is your modpack anyway?

**Comment by Insane-96** [comment]
> All my mod does is write a loot table to the nbt data for the chest. whatever happens after that is out of my hands. I assume the answer is probably yes.
Can I use both loot tables and items?

> What is your modpack anyway?
InsaneVanilla++
Yeah it's in 1.11.2, but I guess the settings will be the same so I can make them in 1.12

**Comment by Terrapin47** [comment]
Would it be possible to include a default setup that simply inherits all the base files, and has examples for adding onto them?  I've been spending a ton of time trying to just add a few things ( loot to levels ) to the dungeons and leaving everything else the way it is, but I can't seem to find a good example or documentation for what is available for me to use to inherit from.  I don't want to re-create the entire dungeon setup in the json files in order to do this.
