### ISSUE TITLE
dimension withelist not work

### ISSUE THREAD

**Issue by christiankarsch** [Greymerk/minecraft-roguelike#134]
I use Mod "Simple Dimensions" to create more dimensions.

Dungeon are generated in all dimensions, if "0" is in whitelist.
Dungeon are not generated in any dimensions, if "0" not in whitelist.

I looked at the code, and found no error at the canSpawnInChunk() and isValidDimension().
Maybe "int dim = editor.getDimension();"returns allways "0".

I continued to search and found the mistake in your WorldEditor class:

@Override
public int getDimension(){
	return world.provider.getDimensionType().getId();
}

use "world.provider.getDimension();" instand!

DimensionType is a enum and contains Nether, Overworld or End;
getID() returns 0 for all Overworld-Dimensions;

**Comment by Greymerk** [comment]
good find. i don't personally use this feature so I wouldn't have noticed. I just tested it against the vanilla dimensions. This dimension id thing has changed several times in minecraft and i guess last time I just fixed it brokenly.

**Comment by Luke616** [comment]
I'm still having this issue in 1.8.0, despite the changelog saying it was fixed. Assuming that I'm not mistyping something in my settings, the dimensionWL or dimensionBL criteria arguments do not seem to work.

For example, THIS dungeon I'm working on is spawning in the overworld despite having a dimensionWL of -100.

 ```
{

	"name" : "magiculture:main_deepdark",
	"exclusive" : true,
	"criteria" : {
		"dimensionWL": -100,
		"weight" : 100
	},
	"inherit" : [
		"magiculture:tower_deepdark",
		"magiculture:layout",
		"magiculture:rooms",
		"magiculture:segments",
		"magiculture:spawners",
		"magiculture:theme",
		"magiculture:loot",
		"magiculture:filters"
	]
}
```
Thanks!

**Comment by Dragnier** [comment]
I'm having an issue where leaving the dimension whitelist in the main config empty always rewrites to have a 0 after I actually load a world, therefore it is not empty to allow generation in any dimension not in the blacklist.
