### ISSUE TITLE
I'm looking to nerf dungeons for Better With Mods

### ISSUE THREAD

**Issue by Ghost8909** [Greymerk/minecraft-roguelike#135]
Though this would include removing glowstone and netherrack from generation. Are those hardcoded into the pieces? Or are they setable with themes?

The fire rooms with braziers and segments with braziers have netherrack, and the cake rooms have glowstone. This breaks the progression the core mod intends to enforce.

**Comment by Alan19** [comment]
You will have to change the theme for the bottom floor to remove the netherrack and then use a room configuration that doesn't include the glowstone rooms

**Comment by Ghost8909** [comment]
The only way is to lose those rooms and segments?

**Comment by nmarshall23** [comment]
I'd would also like to do this. This there a guide of how to remove a theme?
