### ISSUE TITLE
Getting error when generating dungeon

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#139]
I'm getting 
`Failiure: Setting not found: builtin:generator `
whenever I try to generate a dungeon using /roguelike dungeon here. Generating specific structures still work though. I'm on the latest version of 1.12.2.
Settings list:
https://github.com/belathus/Wanderlust-Renewed/tree/master/config/roguelike_dungeons

**Comment by Alan19** [comment]
I seemed to have fixed it by deleting the files I thought were disabled.

**Comment by Caldeiradas** [comment]
Hi! how did you did it? I'm getting:  
`Failiure: Setting not found: fc3:loot1`

**Comment by Alan19** [comment]
You might want to link your config folder, but did you set the namespace to fc3 in that file?

**Comment by Caldeiradas** [comment]
The thing is that is all the same to the original configues but when I run `roguelike settings list` it is missing **fc3:loot1** and the **fc3:loot4**

I can drop my settings here so you can help me better and for your own use ...

**Comment by Alan19** [comment]
I would appreciate that

**Comment by Caldeiradas** [comment]
Sorry I took too long but here they are!  
Just the mods and configues you migth need
[YATM.zip](https://github.com/Greymerk/minecraft-roguelike/files/2752562/YATM.zip)


Tks!

**Comment by Alan19** [comment]
This might be outdated info, but you should use namespace when defining the domain name so it should be
`"namespace":"fc3",
"name":"loot1"`
instead of 
`"name":"fc3:loot1"`

**Comment by Caldeiradas** [comment]
Do you have an functional example?

I created a world just to see the settings and I forgot that thous are costume settings so I would really like to see some done correctly.

btw: I really appreciate your help on this and I'll dig in some information from the wiki is something still doesn't work

**Comment by Caldeiradas** [comment]
I've been comparing what I have to what you sad and the [costume settings](https://github.com/Greymerk/rd-settings) they have here and it looks the same ... Have you tried using the config I gave you?

**Comment by Alan19** [comment]
Here's an example config folder
https://github.com/belathus/Wanderlust-Renewed/tree/master/config/roguelike_dungeons/settings

**Comment by Caldeiradas** [comment]
I just put the link on the previous comment.
The thing that bothers me more is that I'm a programmer and a debugger and I can't find the error either the difference between  the example and my files.

Have you seen them or used them?


@Greymerk , we might need your help on this one. Please.

**Comment by Alan19** [comment]
Have you tried using /roguelike settings reload? I'm getting an error from an incorrect item name from megaloot, but that seems to be because it's not installed. I can't get megaloot to run in my instance as well.

**Comment by Caldeiradas** [comment]
A did the commands, yes ...

**Comment by Alan19** [comment]
I got megaloot to run by installing baubles. Nothing's wrong on my instance. Your custom loot is spawning properly and there's no error when I try to generate dungeons.
