### ISSUE TITLE
Server side crash

### ISSUE THREAD

**Issue by Samuell95** [Greymerk/minecraft-roguelike#14]
Hello, i have crash every time if i started server

Version: 
Roguelike Dungeons: 1.3.5
Forge: 10.13.2.1277

Crashlog: http://icrazy.eu/code/raw/XfLPQrKk

**Comment by Baughn** [comment]
Yup, it's a legit problem all right.

I was able to clear the error by removing the mod, which I *guess* is fine, since there's no client-side elements and I've pregenerated a massive amount of world already. But it'd be good to have it fixed.

**Comment by Greymerk** [comment]
Fixed as of 1.3.6

https://github.com/Greymerk/minecraft-roguelike/blob/v1.3.6/src/main/java/greymerk/roguelike/treasure/loot/Loot.java#L138
