### ISSUE TITLE
NoSuchMethod Crash

### ISSUE THREAD

**Issue by PigheadedGnu** [Greymerk/minecraft-roguelike#15]
https://gist.github.com/PigheadedGnu/f45f683b2e955507f1df

Looks like a problem with a skull? I had this in the only two worlds I generated with this mod.

Cheers!

**Comment by Greymerk** [comment]
It's 1.7.2 version of the mod in 1.7.10 causing the problem.

Just update to a 1.7.10 version of the mod.
