### ISSUE TITLE
Question about dungeon generation

### ISSUE THREAD

**Issue by NovaRobin** [Greymerk/minecraft-roguelike#154]
I wanted to use this mod on a server with my girlfriend, but due to issues, we decided to use Realms instead, so mods don't really work. But, I decided to try and generate a world in my Forge singleplayer, then use that world in Realms. It worked! We are now the proud inhabitants of a tower hiding a seemingly endless labyrinth of magic and mayhem. But, there's a question still unanswered; Are there other dungeons?

I guess my question is; Do all the dungeons generate when you create the world, or do they generate when you get near where they could be? I don't know anything about how structure generation works in Minecraft, so this could be a pretty dumb question, but I really don't know.

**Comment by Alan19** [comment]
They only generate when you get close to them. You can try using a chunk pregenerator mod to get more to generate though.
