### ISSUE TITLE
precious blocks=false being ignored

### ISSUE THREAD

**Issue by mattrix444** [Greymerk/minecraft-roguelike#155]
I'm assuming this setting stops towers from being made from emerald blocks etc? but i turn it off and it doesn't seem to do anything. as far as I'm aware i don't have anything altering roguelikes at all.
using 1.12.2 1.8.0 version. thanks

**Comment by Greymerk** [comment]
At the moment all it does is prevent diamond/gold blocks from spawning on the nether floor.

If you've changed the configuration to use the setting "random=true" then you will get bizarre structures made out of diamond blocks either way. It's meant as a joke setting.

**Comment by mattrix444** [comment]
oh right. i have random and precious blocks both set to false so not sure whats happening
