### ISSUE TITLE
Possible bug: "Empty" dungeons in "unknown"/"unusual" biomes!?

### ISSUE THREAD

**Issue by chland** [Greymerk/minecraft-roguelike#158]
I'm currently playing around with the latest version of RD (1.8.0) for MC 1.12.2 and stumbled across an interesting behaviour.

I was testing some stuff in my custom modpack which uses Biome Bundle and I noticed a few rather strange dungeons. They use the default stonebrick-tower above ground (the round one) and all passages/rooms underground are made out of stonebricks.

The strange thing is, that no spawners and no chests were generated. Here is a screenshot of one of those dungeons:

![rd_bug](https://user-images.githubusercontent.com/472894/40590103-6d691452-61f9-11e8-80e7-5604ad24fa50.jpg)

My first thought was that it might be related to Biome Bundle and i was "kinda" right. I jumped into a simple modpack with only RD in it and did some tests. Basically those "strange" dungeons seem to generate if dungeons are created in "unexpected" biomes. For exmaple: when I tried to generate one in a plains / desert / etc. biome everything was fine but in a Deep Ocean I got one of the messed up dungeons.

My guess is that RD selects certain settings based upon the biome where the dungeon generates and if it doesn't know the biome it falls back to some kind of basic set of settings. And while I'm OK with that it would be nice if those would contain spawners and chests :)

Is there an easy way to fix this using the settings?

**Comment by chland** [comment]
Upon further investigation, one problem seems to be that rooms aren't really generating at all. The "broken" dungeons only contain corridors, crossings and those small "rooms" at dead-ends but no real rooms:

![rd_bug_2](https://user-images.githubusercontent.com/472894/40590404-81fbe2d2-61fe-11e8-8f0f-3a8e4a93e80e.jpg)

**Comment by Axieum** [comment]
Can confirm, have run into a couple of these styles of buildings. I initially thought that they might generate on purpose for those who want to live in a scaffolding one.

I saw in the configuration that there is a "scaffolding" type of dungeon.

**Comment by Greymerk** [comment]
I found this myself actually and it's already fixed in dev. With the fix the dungeon will just fail to generate at all if there are no settings available for the spawn location.

**Comment by chland** [comment]
Awesome :) And thanks for the info.
