### ISSUE TITLE
[1.7.10] Crash with Fastcraft (or so it seems)

### ISSUE THREAD

**Issue by Zundrel** [Greymerk/minecraft-roguelike#16]
Hello! I've been trying to use your mod lately and I've been getting this crash upon trying to create a world: http://pastebin.com/Zf0Emp2S

It looks like it is Fastcraft and your mod causing the issue, but I'm not entirely sure. If you could possibly look into a fix for this it would be great.

**Comment by Adaptivity** [comment]
Vanilla MC bug. Was fixed in latest Forge by: https://github.com/MinecraftForge/MinecraftForge/commit/9704f25aa89415c2bb4ca4dd932a0ef8849ddf9e
