### ISSUE TITLE
Utilizing MegaLoot

### ISSUE THREAD

**Issue by Budhvin** [Greymerk/minecraft-roguelike#160]
Hi

I have been trying to use mega loot items, and have the spawn in the game. I am unsure what I am doing wrong. I keep getting Not a Json Object : Null. Here is the code I am using.

https://pastebin.com/4XgX9x8v

**Comment by JohnLouderback** [comment]
@Budhvin You have quite a few syntax errors in your JSON. Run it through a JSON validator to see what I mean. It's mostly trailing commas and escaped quotes.
