### ISSUE TITLE
Lava Take over on lowest level

### ISSUE THREAD

**Issue by taylor1324** [Greymerk/minecraft-roguelike#161]
1.12.2 version. Lowest level (nether level) sometimes has rooms and/or hallways that are filled with lava for no reason. this occurs with other mods as well as with only RLD installed. This seems to cause rooms like the super chest room (the one with the stairs and 8 chests) to not spawn chests.

Hallway:
![2018-06-04_18 36 42](https://user-images.githubusercontent.com/24307151/41472716-46d42684-7085-11e8-8db0-a8a045920210.png)

The super chest room:
![2018-06-04_19 24 46](https://user-images.githubusercontent.com/24307151/41472664-17fd4e12-7085-11e8-85e2-a9fd46972449.png)

**Comment by DemonfangArun** [comment]
Well I see I'm not the only one with this problem. I'm guessing either air is not being saved as air, or that the dungeons are generating before the lava.

**Comment by DemonfangArun** [comment]
Adding onto this, dungeons mess up a LOT, even on upper levels. I think there's an order of operations issue, and caves are generating AFTER dungeons (and other things are too). Maybe putting generation later in the chunk generation operations would be a good idea.
