### ISSUE TITLE
Can't get modded items to spawn? Settings not overriding?

### ISSUE THREAD

**Issue by aridhol** [Greymerk/minecraft-roguelike#162]
No matter what I do, I can't get my settings to overwrite the built in loot rules?

I think that's what happening, anyway - In game I can reload and list settings using the commands and it shows my settings, but it also shows the builtin:loot. Mine is shown under default:loot. But none of my loot rules seem to be taking any effect at all?

Is there some way to force your rules into effect, am I missing something that should be obvious? Can anyone help?

I have attached a sample of my loot rules, for my loot_all.json - the first 80% or so is the default settings that are given to us as an example, the last few are mine. 

Any assistance would be much appreciated!

```
{
	"name" : "loot_all",
	"loot_rules" : [
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "FOOD",
			"loot" : [
				{"data" : {"name" : "minecraft:cookie", "min" : 2, "max" : 8}, "weight" : 1},
				{"data" : {"name" : "minecraft:bread", "min" : 1, "max" : 3}, "weight" : 5},
				{"data" : {"name" : "minecraft:apple"}, "weight" : 1},
				{"data" : {"name" : "minecraft:cooked_porkchop"}, "weight" : 2},
				{"data" : {"name" : "minecraft:cooked_chicken"}, "weight" : 2},
				{"data" : {"name" : "minecraft:cooked_beef"}, "weight" : 2},
				{"data" : {"name" : "minecraft:cooked_rabbit"}, "weight" : 1},
				{"data" : {"name" : "minecraft:cooked_fish"}, "weight" : 1},
				{"data" : {"name" : "minecraft:baked_potato"}, "weight" : 1},
				{"data" : {"name" : "minecraft:rabbit_stew"}, "weight" : 1},
				{"data" : {"name" : "minecraft:mushroom_stew"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 3
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "POTIONS",
			"loot" : [
				{"data" : {"type" : "potion", "name" : "strength"}, "weight" : 1},
				{"data" : {"type" : "potion", "name" : "regeneration"}, "weight" : 1},
				{"data" : {"type" : "potion", "name" : "leaping"}, "weight" : 1},
				{"data" : {"type" : "potion", "name" : "night_vision"}, "weight" : 1},
				{"data" : {"type" : "potion", "name" : "fire_resistance"}, "weight" : 1},
				{"data" : {"type" : "potion", "name" : "swiftness"}, "weight" : 1},
				{"data" : {"type" : "potion", "name" : "healing"}, "weight" : 1}
				
			],
			"each" : true,
			"quantity" : 4
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "MUSIC",
			"loot" : [
				{"data" : {"name" : "minecraft:record_cat"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "SUPPLIES",
			"loot" : [
				{"data" : {"name" : "minecraft:wheat_seeds"}, "weight" : 1},
				{"data" : {"name" : "minecraft:wooden_hoe"}, "weight" : 1},
				{"data" : {"name" : "minecraft:pumpkin_seeds"}, "weight" : 1},
				{"data" : {"name" : "minecraft:melon_seeds"}, "weight" : 1},
				{"data" : {"name" : "minecraft:lead"}, "weight" : 1},
				{"data" : {"name" : "minecraft:wheat"}, "weight" : 1},
				{"data" : {"name" : "minecraft:beetroot_seeds"}, "weight" : 1},
				{"data" : {"name" : "minecraft:sapling"}, "weight" : 1},
				{"data" : {"name" : "minecraft:torch", "min" : 5, "max" : 20}, "weight" : 3}
			],
			"each" : true,
			"quantity" : 2
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "SMITH",
			"loot" : [
				{"data" : {"type" : "specialty", "equipment": "sword", "quality" : "iron", "level" : 1}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "STARTER",
			"loot" : [
				{"data" : {"type" : "mixture", "name" : "coffee"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "STARTER",
			"loot" : [
				{"data" : {"type" : "specialty", "equipment" : "legs", "quality" : "wood", "level" : 1}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 2
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "STARTER",
			"loot" : [
				{"data" : {"type" : "tool", "level" : 1}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 2
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "STARTER",
			"loot" : [
				{"data" : {"type" : "weapon", "level" : 1}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 2
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "STARTER",
			"loot" : [
				{"data" : {"name" : "minecraft:stick", "nbt" : "{display:{Name:\"Twig\",Lore:[\"A little twiggy\"]}}"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "BLOCKS",
			"loot" : [
				{"data" : {"name" : "minecraft:cobblestone", "min" : 20, "max" : 40}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},		
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "BREWING",
			"loot" : [
				{"data" : {"name" : "minecraft:blaze_powder"}, "weight" : 1},
				{"data" : {"name" : "minecraft:fermented_spider_eye"}, "weight" : 1},
				{"data" : {"name" : "minecraft:spider_eye"}, "weight" : 1},
				{"data" : {"name" : "minecraft:magma_cream"}, "weight" : 1},
				{"data" : {"name" : "minecraft:speckled_melon"}, "weight" : 1},
				{"data" : {"name" : "minecraft:ghast_tear"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 8
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "BREWING",
			"loot" : [
				{"data" : {"name" : "minecraft:glass_bottle", "min" : 2, "max" : 7}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 2
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "ENCHANTING",
			"loot" : [
				{"data" : {"name" : "minecraft:experience_bottle", "min" : 5, "max" : 15}, "weight" : 2},
				{"data" : {"name" : "minecraft:book", "min" : 1, "max" : 3}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "WEAPONS",
			"loot" : [
				{"data" : {"type" : "potion", "name" : "strong_strength"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
		{
			"level" : [0, 1, 2, 3, 4],
			"type" : "ARMOUR",
			"loot" : [
				{"data" : {"type" : "potion", "name" : "long_regeneration"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
        {
			"level" : [0, 1, 2, 3, 4],
            "type" : "ARMOUR",
			"loot" : [
				{"data" : {"name" : "ebwizardry:wizard_hat" }, "weight" : 3},
                {"data" : {"name" : "ebwizardry:wizard_hat_fire" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_hat_ice" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_hat_lightning" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_hat_necromancy" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_hat_earth" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_hat_sorcery" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_hat_healing" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_robe" }, "weight" : 3},
                {"data" : {"name" : "ebwizardry:wizard_robe_fire" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_robe_ice" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_robe_lightning" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_robe_necromancy" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_robe_earth" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_robe_sorcery" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_robe_healing" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_leggings" }, "weight" : 3},
                {"data" : {"name" : "ebwizardry:wizard_leggings_fire" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_leggings_ice" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_leggings_lightning" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_leggings_necromancy" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_leggings_earth" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_leggings_sorcery" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_leggings_healing" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_boots" }, "weight" : 3},
                {"data" : {"name" : "ebwizardry:wizard_boots_fire" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_boots_ice" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_boots_lightning" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_boots_necromancy" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_boots_earth" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_boots_sorcery" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:wizard_boots_healing" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:armour_upgrade" }, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
        {
			"level" : [0, 1, 2, 3, 4],
            "type" : "WEAPONS",
			"loot" : [
				{"data" : {"name" : "ebwizardry:magic_wand" }, "weight" : 2},
                {"data" : {"name" : "ebwizardry:basic_fire_wand" }, "weight" : 1},
                {"data" : {"name" : "ebwizardry:basic_ice_wand" }, "weight" : 1},
                {"data" : {"name" : "ebwizardry:basic_lightning_wand" }, "weight" : 1},
                {"data" : {"name" : "ebwizardry:basic_necromancy_wand" }, "weight" : 1},
                {"data" : {"name" : "ebwizardry:basic_earth_wand" }, "weight" : 1},
                {"data" : {"name" : "ebwizardry:basic_healing_wand" }, "weight" : 1},
                {"data" : {"name" : "ebwizardry:basic_sorcery_wand" }, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
        {
			"level" : [0, 1, 2, 3, 4],
            "type" : "ENCHANTING",
			"loot" : [
                {"data" : {"name" : "ebwizardry:arcane_tome", "meta" : 1}, "weight" : 3},
                {"data" : {"name" : "ebwizardry:arcane_tome", "meta" : 2}, "weight" : 2},
                {"data" : {"name" : "ebwizardry:arcane_tome", "meta" : 3}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
        {
			"level" : [0, 1, 2, 3, 4],
            "type" : "ENCHANTING",
			"loot" : [
                {"data" : {"name" : "ebwizardry:condenser_upgrade"}, "weight" : 1},
                {"data" : {"name" : "ebwizardry:siphon_upgrade"}, "weight" : 1},
                {"data" : {"name" : "ebwizardry:storage_upgrade"}, "weight" : 1},
                {"data" : {"name" : "ebwizardry:range_upgrade"}, "weight" : 1},
                {"data" : {"name" : "ebwizardry:duration_upgrade"}, "weight" : 1},
                {"data" : {"name" : "ebwizardry:cooldown_upgrade"}, "weight" : 1},
                {"data" : {"name" : "ebwizardry:attunement_upgrade"}, "weight" : 1},
                {"data" : {"name" : "ebwizardry:blast_upgrade"}, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
        {
			"level" : [0, 1, 2, 3, 4],
            "type" : "SUPPLIES",
			"loot" : [
				{"data" : {"name" : "ebwizardry:identification_scroll" }, "weight" : 1}
			],
			"each" : true,
			"quantity" : 1
		},
        {
			"level" : [0, 1, 2, 3, 4],
			"loot" : [
				{"data" : {"name" : "minecraft:stick"}, "weight" : 2},
				{"data" : {"name" : "minecraft:slime_ball"}, "weight" : 1},
				{"data" : {"name" : "minecraft:clay_ball"}, "weight" : 1},
				{"data" : {"name" : "minecraft:bone"}, "weight" : 1},
				{"data" : {"name" : "minecraft:string"}, "weight" : 1},
				{"data" : {"name" : "minecraft:snowball"}, "weight" : 1},
				{"data" : {"name" : "minecraft:feather"}, "weight" : 1},
				{"data" : {"name" : "minecraft:torch", "min" : 7, "max" : 19}, "weight" : 3}
			],
			"each" : true,
			"quantity" : 4
		}
	]
}
```

**Comment by aridhol** [comment]
Editted a few times to clean up the code for easier reading in here. As far as I can tell, I have no .json formatting issues, I'm using Brackets to do the editting and it throws a fit if you make a mistake. And as I said, I can reload settings and it succeeds (I know what it looks like when it fails, trust me... Trial and error!)

**Comment by Alan19** [comment]
Have you used /roguelike settings reload t ocheck if the jsons are correct?

**Comment by aridhol** [comment]
@Alan19 you must have missed it in my comment above, but yes, I have used /roguelike settings reload and I have no problems. It reloads just fine and shows up in the list. I had issues for awhile that I worked through, but now even with properly done json's, it still seems not to work.

Is there some way to force the loot to use the custom rules over the built in? I mean, I assumed that it did that automatically... but, here we are

**Comment by Alan19** [comment]
You can try making a custom dungeon that inherits this file.

**Comment by aridhol** [comment]
Okay - so my overall loot file (the one that inherits all the other loot files - its the same structure as the default example given - is called "wiz-loot.json"

So, when I run the command "/roguelike dungeon here wiz-loot " to attempt to force the dungeon to load with those loot rules, it loads a dungeon that is completely empty of all spawners and loot, and is made 100% of stone brick with no adornments of any kind. 

I'm guessing I'm getting closer to the problem now. 

Based on this, if I'm correct, if you only put loot rules into your settings, it doesn't automatically inherit the default dungeon spawning rules? That seems... wrong.

I don't want to change the dungeons at all - they are great. All I want is to customize the loot rules a bit - what the heck is going on, and how do I make it right??

**Comment by Alan19** [comment]
You need to have it inheirit the builtin settings. Check the examples repo if you need more help.

https://github.com/Greymerk/rd-settings/blob/master/main.json

**Comment by aridhol** [comment]
That example is lacking however, the demo files are only an example of a basic tower - I want to inherit the built in setup. Can I somehow tell it to inherit and use those rules? There is no example of how to do that as far as I can see

**Comment by aridhol** [comment]
Hey, I've made progress! Its a start. Not perfect yet, things are behaving... strangely. But dungeons are generating now via the command - in my testing so far my loot is not being injected into the dungeons that spawn on their own, however, no idea why that is or how to change it

Also, ebwizardry has some loot functions that allow his spell books to receive a random spell - this function doesn't appear to be working when used in conjunction with this mod. 

Does this mod support json loot functions?

**Comment by aridhol** [comment]
Two observations before I'm off for the night -

My loot rules work only when I manually spawn a dungeon in,  the default dungeons do not inherit the rules - what did I do wrong?

Also - My loot chests are INSANELY overstuffed - I did not add very much at all, and in fact took out a lot of the default stuff, its like its adding in the loot rules from my settings to the default and essentially doubling the loot; every chest in the dungeon is completely full of loot, in every slot. Thoughts as to why that might be happening?

Lastly - I noticed an option for "overrides" in the documentation but it isn't actually explained, the link is dead. Am I looking for that? How do I get the syntax right, if so?

Thanks all

**Comment by Alan19** [comment]
I don't think the mod supports loot functions. However, from what I can tell from the documentation GitHub, they support adding loot tables but it's very buggy. I tried adding a loot table with randomized EBWizardry books and it ended up filling the chest with the original loot table contents.

**Comment by Alan19** [comment]
For the overstuffing, you might want to set exclusive to true.

**Comment by Alan19** [comment]
Did you give your custom dungeon a spawning criteria?

**Comment by aridhol** [comment]
That's the thing - I don't want a custom dungeon at all, I ONLY want to change the loot for the default dungeons. I've seen a video (of a 1.7.10 version, to be fair) and it was easy to do, simply go in and change the lines in the settings and away you go.

That's all I want to do - why is it so complicated? I feel like the way this is implemented is very poorly done. Either that, or the documentation is outdated and I'm just missing something entirely

**Comment by aridhol** [comment]
I found a modpack using Roguelike and custom settings, Magiculture 2, and upon looking at his settings....

I have no idea why mine aren't working. They are different, but the structure is the same, and he has NOTHING about dungeon rules or anything, he only changed the loot and thats all he has in his settings folder and it works fine. Why doesn't mine??! And I checked, the pack has the same version of Roguelike as I do.

I'm at a complete loss here

**Comment by aridhol** [comment]
Well - for what appears to be no reason at all, I've got it working. I *THINK* I might have an idea why mine weren't working - my loot tables all had the same names they were originally given via the demo files - meaning, the same names as the tables already being looked up? So perhaps it wasn't looking at them?

I changed some names around and condensed it into a single loot file and tada, working. 

Of course, the spell book problem is still a thing - without the ability to call loot functions, I'm not sure how I'm going to get around that one..

**Comment by aridhol** [comment]
There is an example of "Loot Tables" being used, and being able to call vanilla dungeon loot tables - how does this work exactly? If I set one up in my settings file it doesn't show up in my "/roguelike settings list" but my reload works fine so I'm not sure if its working but not showing, or if loot tables are currently not actually supported?

Ebwizardry extends the vanilla loot table so if I could call that for bonus loot, that work work great for me. 

Anyone know how to structure the loot table settings?

**Comment by aridhol** [comment]
Copying from Grey's comment awhile back on loot tables:
{
	"name" : "test:loot",
	"criteria" : {},
	"overrides" : [
		"LOOTRULES"
	],
	"loot_tables" : [
		{"table" : "minecraft:chests/simple_dungeon"}
	]
}

I tweaked it so levels 0-2 have simple dungeon, 3 is mineshaft, 4 is desert pyramid. Works great far as I can tell!

With one weird exception - it seems to have also overridden the special spawner rules? My zombies and skeletons down in the dungeons don't spawn with interesting gear / shields now :( 

Not a huge deal, but it reduces flavor by a smidge

**Comment by aridhol** [comment]
This issue is pretty much closed, I don't really see much reason to keep it open - though I still don't know why it didn't work in the first place :P

**Comment by Terrapin47** [comment]
I can give you a potential answer for the reason your dungeon spawned in empty ( just for reference ).  When using the command to spawn a dungeon, if the biome you are in isn't supported it will generate a blank one.
