### ISSUE TITLE
Crash while exploring, something about a jukebox.

### ISSUE THREAD

**Issue by Darkmega18** [Greymerk/minecraft-roguelike#164]
[crash-2018-06-22_01.29.56-server.txt](https://github.com/Greymerk/minecraft-roguelike/files/2126462/crash-2018-06-22_01.29.56-server.txt)

You're the only mod that I know off the top of my head that has the possibility of spawning a jukebox in it's generation, so I'm posting this here. Would you have any idea what this crash is about? it's been bothering me for some time, but I usually just let it go cause it rights itself the next time the game loads. But it feels spaced out enough that it could be your dungeons and possibly something screwing up in newer versions of forge since your last update on curse was end of 2017. :V it happened on server, but it also happens on singleplayer also and usually takes the entire game with it.

**Comment by Darkmega18** [comment]
Uh. welp. ok? nothing?

**Comment by Greymerk** [comment]
Sorry for not responding to your issue six years ago. I looked at your crash log and I can't make anything of it anyway. I'm fairly certain it had nothing to do with my mod.

**Comment by Darkmega18** [comment]
ah I see. was a fair while gone anyways.
