### ISSUE TITLE
Is there a reason this has to be installed on the client?

### ISSUE THREAD

**Issue by Vekseid** [Greymerk/minecraft-roguelike#17]
As far as I can tell it doesn't add any non-vanilla content.

**Comment by Greymerk** [comment]
It could be I just configured something wrong. I am not an expert on forge itself. So likely this is my bad.

**Comment by Vekseid** [comment]
https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/Mod.java

I believe you need to set acceptableRemoteVersions to "*"

Still fairly new at this myself.

**Comment by Vekseid** [comment]
In RogueLike.java, replace

@Mod(modid="Roguelike", name="Roguelike Dungeons", version=Roguelike.version)

with

@Mod(modid="Roguelike", name="Roguelike Dungeons", version=Roguelike.version, acceptableRemoteVersions="*")

**Comment by Greymerk** [comment]
I'll add that in for next update. Thanks for pointing it out.

**Comment by Adaptivity** [comment]
You are forgot to add acceptableRemoteVersions="*" to 1.7.10 version. Or it not needed anymore?

**Comment by Greymerk** [comment]
You're right. I added it into what became the 1.8 (master) branch and then it wound up not being in the 1.7 maintenance branch. Wasn't intentional, just happened because of the split.

**Comment by Greymerk** [comment]
Will be in the next release. I've since bridged the 1.7/1.8 versions so they're easier to keep up to date now.

**Comment by Badcholo** [comment]
Can i remove the mod from the client or does it still need it?
