### ISSUE TITLE
Dungeons are empty

### ISSUE THREAD

**Issue by SchliffedGamer** [Greymerk/minecraft-roguelike#170]
When I play this mod in 1.12.2 (Version 1.12.2-1.8.0), the dungeons are completly empty and only made with stonebrick. I couldn't find any chest in the entire dungeon.

Screenshots:
![2018-09-07_16 15 19](https://user-images.githubusercontent.com/39455177/45224364-18879500-b2ba-11e8-8221-a39b54d42199.png)
![2018-09-07_16 15 56](https://user-images.githubusercontent.com/39455177/45224365-18879500-b2ba-11e8-9d36-52ab9affc2bd.png)
![2018-09-07_16 16 46](https://user-images.githubusercontent.com/39455177/45224366-18879500-b2ba-11e8-9ed3-8123f89b50d2.png)

It's a game-breaking glitch which already destroyed the generated chunks in my world.

**Comment by BrisingrAerowing** [comment]
Did you customize the dungeon configs? This is caused when the config files have errors, like a trailing comma.

**Comment by stormbringerGT** [comment]
I noticed this happens in Dungeons that create close to world spawn, and in modded Biomes (I see the empty dungeons consistently on the Landfill Biome from Dumpster Diving and other Biome O Plenty, consistently in the Marsh biome for example.

**Comment by srwaggon** [comment]
@SchliffedGamer 
@BrisingrAerowing 
@stormbringerGT 
I was able to fix this in my own fork of Roguelike Dungeons:

https://www.curseforge.com/minecraft/mc-mods/roguelike-dungeons-fnar-edition
