### ISSUE TITLE
Strange Items in Fireworks dispenser

### ISSUE THREAD

**Issue by fandomaniac** [Greymerk/minecraft-roguelike#173]
I'm finding sticks and hoes in some fireworks' room dispensers. See screen-captures below. I'm running Roguelike Dungeons 1.12.2-1.8.0 on a SMP server running Forge 1.12.2-14.23.5.2769.

![2018-10-23_21 18 58](https://user-images.githubusercontent.com/37810246/47440982-4434e080-d77d-11e8-99c8-f1c5d7a6c9c3.png)
![2018-10-23_21 19 00](https://user-images.githubusercontent.com/37810246/47440998-4ac35800-d77d-11e8-94f7-baf8909add75.png)
![2018-10-23_21 19 05](https://user-images.githubusercontent.com/37810246/47441029-59117400-d77d-11e8-89bc-e3dd134f92ab.png)

**Comment by BrisingrAerowing** [comment]
The actual fireworks dispensers are on the surface. That's the control room, and those items give a 1 in 9 chance of the respective firework dispenser actually going off.
