### ISSUE TITLE
[Question] Multiple customized dungeon types

### ISSUE THREAD

**Issue by Morinor** [Greymerk/minecraft-roguelike#176]
Is there a way to add multiple custom dungeon types?
There can only be one "settings" folder, and you cant have duplicate file names,
and adding another segment of settings at the end of every json file doesnt seem to work either.

Is there some way to have multiple custom dungeons, or is it just impossible?

**Comment by Alan19** [comment]
You can make multiple files with different names and they will all have an equal chance of generating if they are weighted equally without spawning criteria. 

https://github.com/belathus/Wanderlust-Renewed/tree/master/config/roguelike_dungeons/settings
