### ISSUE TITLE
[BUG] Blank Enchanting Books

### ISSUE THREAD

**Issue by ghost** [Greymerk/minecraft-roguelike#177]
**Minecraft Version:** 1.12.2
**Minecraft Forge Version:** 14.23.5.2796 [Latest as of 22/12/18]
**Rogue-Like Dungeons Version:** 1.8.0
**Java Version:** Version 8 Update 191 [64 bit]

**Our server is using SpongeForge Version:** 1.12.2-2768-7.1.5-RC3512

Players report on my Server that upon raiding a Rogue Dungeon sometimes they will loot chests with blank enchanting books. These books are literally just called "_Enchanting Book_" with no traits or benefits of even having them.

**This issue is not serious, or even remotely report-worthy,** but its nice to bring issues to Developers' Notice.

_**You can see a blank enchanting book that a user got here:**_
![image](https://user-images.githubusercontent.com/44342726/50375241-45a24e00-05f2-11e9-9142-03b1be2c19b3.png)

**Comment by 0xEviqnn** [comment]
Edited because I sent the wrong screenshot.
