### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by wolfgangrumpf** [Greymerk/minecraft-roguelike#181]
Using the latest version of Roguelike Dungeons (1.12.2-1.8.0) I started getting an endless stream of this error to my log file:

Roguelike Dungeons loaded a new chunk [114, 12] in dimension 0 (overworld) while populating chunk 
[113, 9], causing cascading worldgen lag.
[15:26:54] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[15:26:54] [Server thread/WARN] [FML]: Roguelike Dungeons loaded a new chunk [113, 12] in dimension 0 (overworld) while populating chunk 
[113, 9], causing cascading worldgen lag.

**Comment by BaccarWozat** [comment]
Am getting the exact same thing (different chunks). I am using a lot of other mods though.
Forge 2776, Roguelike 1.8.0
It happened when I entered a new area deep to the south of spawn. I was in a boat for some of it, suggesting it was mispopulating because I was loading chunks quickly. I also have a render distance of 24 which probably added to that.

**Comment by MentalMouse** [comment]
Yes, whenever RLD generates a dungeon, it needs to populate all the chunks the dungeon extends into.  This is an occasional performance hit as you explore, but that's the price of having the dungeons in your world.

**Comment by Trnrr** [comment]
If you pregen your world you wont have this issue. Other than that I don't think there's a way to fix it.

**Comment by SeamusMullan** [comment]
Just a bump for this as its still a large issue. When running a server with other mods it gets hard to pregen all the chunks that players will explore effectively and breaks other mod structures.

Theres a way to do this roughly outlined here:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/3126131-question-how-to-get-rid-of-cascading-worldgen-lag

Hope to see this fix come out eventually if it does (and if its possible ofc)
