### ISSUE TITLE
[Request] Default Roguelike Dungeons loot setting .json files

### ISSUE THREAD

**Issue by Nakuta** [Greymerk/minecraft-roguelike#182]
I intend to customize the loot tables for RD on my server, but I'd prefer to start from the defaults built into the mod and add from there.  Do the demo .json files match the default RD loot settings, and if not where can I obtain ones that do?

Additionally, I'm seeing lots of questions about custom loot issues go unanswered for months, is this not the correct place to be asking for help with this mod?

Thank you

**Comment by TheAwesomeGem** [comment]
Same here :(
