### ISSUE TITLE
[Suggestion] Update to 1.13.2

### ISSUE THREAD

**Issue by Drc-DEV** [Greymerk/minecraft-roguelike#183]
Update version to 1.13.2

**Comment by Block-Vader** [comment]
Minecraft forge for 1.13 is not released yet. It will take quite some time before first mods will start updating to 1.13

**Comment by Drc-DEV** [comment]
If you want to start getting it ready for 1.13.2, here's the forge alphas: https://files.minecraftforge.net/maven/net/minecraftforge/test/forge/index_1.13.html

**Comment by rikka0w0** [comment]
now Forge 1.15.2 is comming
