### ISSUE TITLE
How to I remove an advancement level?

### ISSUE THREAD

**Issue by gzcwnk** [Greymerk/minecraft-roguelike#184]
Ive gone 1 level? too high on mining and now I mine 9 blocks at once which is ruining the game, its now un-playable. :(

Is there a user file to edit somewhere?

**Comment by MentalMouse** [comment]
There's a ritual to let you strip all your advancements (they come out as "books" you can re-add to the chestplate).  There's another (Penitence) that I think lets you block advancements, but I haven't tried it because it's not clear what it would actually do for me.

**Comment by gzcwnk** [comment]
Thanks, I was / am assuming there is a user config file somewhere that holds this info and I can edit it.

Trouble is with google you have to hit the right terms/syntax sometimes to get a reply that makes sense, I didnt this time.  Got to the stage I was about to wipe the mod and go try another.  

Anyway I dont know what happened but all of a sudden I went back to mining 1 block and not 9.  Possibly a hotkey?   but I cant find it after hours of googling etc.
