### ISSUE TITLE
[Question] Configs and Removing/Disabling Rooms

### ISSUE THREAD

**Issue by ElsaTheHobo** [Greymerk/minecraft-roguelike#186]
Hello! I love this mod and think it's awesome. One thing I don't like, however, is the Spider cobweb rooms. I just don't think they're fun and I wanna get rid of them with the config. However, there doesn't seem to be a simple way to do this. I tried downloading the demo_rooms.json (or whatever it's called) and removing the spider room, but it appears to have only removed them from the basic dungeon (not the desert one, and I haven't checked out any other ones). Is there an easy way to disable rooms from showing up at all, in any theme, other than just creating replacement configs for every variant of Dungeon?

I named the json builtin:rooms in an attempt to overwrite the default one, as the Wiki documentary does not tell me how, or if it's possible, to overwrite the builtin settings, though now there are duplicates of rooms that should only show up once. I assume this has to do with inheritance or merging of the two settings. How do I properly overwrite built-in settings?

**Comment by Alan19** [comment]
f I recall correctly, if you want to override the room configuration, you will have to make a new dungeon and use a custom room setup. However, this means you have to make your own dungeons as it overwrites the default dungeons.
