### ISSUE TITLE
Overlapping Generation & Dynamic Trees

### ISSUE THREAD

**Issue by Avery93** [Greymerk/minecraft-roguelike#187]
Roguelike dungeons that spawn naturally seem to have a bad habit of overlapping with other structures, like trees and villages. To an extent, this is probably unavoidable and ultimately tolerable. However, something weird happens when they overlap spatially with blocks generated by Dynamic Trees. The dungeon overrides the tree, destroying the blocks but leaving invisible and impassable glitched space in their place. I have no clue which mod is responsible, but it is exclusively at the intersection of these two mods that this occurs so I will submit it to both threads.

Is there a config somewhere I'm missing that makes the above ground portions more context-aware regarding other existing structures?

**Comment by MentalMouse** [comment]
Hmm.  "invisible and impassable glitched space" usually indicates a client/server desync.  What happens there when you exit and reload the world?

**Comment by Avery93** [comment]
Ah! You got it, I didn't even think that would be an issue since I'm only playing single player, but the client does indeed set up an internal server. Rebooting resolved the conflict by getting rid of the tree and restoring the structure.
