### ISSUE TITLE
Treasure Urn reward duplication.

### ISSUE THREAD

**Issue by Kuponutmog** [Greymerk/minecraft-roguelike#193]
Installed 1.30 fresh as a server. Did the quest book line which involves smelting a gold bar and got the treasure urn loot from that quest. Not sure if intended but you can place this urn down many times and obtain loot, (managed to place it down 20+ times so assuming infinately?)

**Comment by srwaggon** [comment]
@Kuponutmog I think your issue is with the Roguelike Dungeons & Adventures mod, rather than this mod with the similar name, Roguelike Dungeons. I think you can close this issue and open one with that modpack.
