### ISSUE TITLE
OK, so this seems to be the problem everyone is having can we address it right here.

### ISSUE THREAD

**Issue by G-BOI-HERE** [Greymerk/minecraft-roguelike#198]
It seems that everyone, myself included, would like to know how to integrate their own custom loot tables for each level into the already existing dungeons. To my own knowledge i understand that there are some overrides that are not posted on this wiki and are kinda a secret, they are 100% needed knowledge for modpack makers as we have not much know how to go off of as for what to include in the "demo" files in order to get them to function fully... any knowledge is appreciated, especially that of @Greymerk seeing as you are the creator & @Alan19 as you seem to have the most insight on resolving the issues posted on this forum.

**Comment by Alan19** [comment]
I tend to avoid using loot tables for this mod because it seems like using a loot table would have the entire floor using that loot table and override any normal loot you specified in the JSON.

**Comment by G-BOI-HERE** [comment]
@Alan19 I was able to get the loot to spawn in correctly myself, the only thing i cant get it to do is work in all the dungeons that are already existing within the mod, and will only work with one dungeon at a time as is specified in "main.json" and "towers.json", main being the criteria in which biomes the towers spawn in and towers being the towers that spawn in... i believe that if i was able to specify which tower spawns in which biome and not only be able to use a single tower (when i try adding more towers it defaults to the last one in the load list), then the problem may be fixed, i am just having trouble with this part as i dont know if i would need to input in overrides for said towers to inheret the original towers spawn criteria and replace them.

**Comment by G-BOI-HERE** [comment]
Also i realize that this is taking time out of your day but seeing as this is a mod that many modpack creators opt to use, if we can get this solved i will try to help resolve the problems here on this forum for the other users running into the same problems.

**Comment by Alan19** [comment]
I am not sure how to get loot settings to apply to the existing dungeons generated by Roguelike Dungeons, nor apply them to all the different types of dungeons generated by the mod. When I made custom loot, I ended up overriding all of the towers and replacing it with my own. However, this means you won't be seeing any towers except for the default one.

You should be able to get a list of all of the overrides if you take a look at the code.

**Comment by G-BOI-HERE** [comment]
ok, thank you!
