### ISSUE TITLE
Cascading WorldGen Lag

### ISSUE THREAD

**Issue by Super-Shimzy** [Greymerk/minecraft-roguelike#200]
[New Paste 1.txt](https://github.com/Greymerk/minecraft-roguelike/files/3800897/New.Paste.1.txt)

Because this mod has custom worldgen it's causing cascading worldgen lag from generating into populated chunks.

**Comment by ImSpacee** [comment]
This is bound to happen, I would recommend using Dungeons2! as they appear to have primarily solved the issue.

If not, you can always pre-generate the world.

**Comment by TheCrudNation** [comment]
Also getting this issue. Would love to know a fix, I'm unable to pre-gen the world for various reasons.
