### ISSUE TITLE
Noob Request

### ISSUE THREAD

**Issue by Skabbety** [Greymerk/minecraft-roguelike#208]
A Noob Question but, how do I spawn a regular dungeon with no altered settings because I am having so much trouble. I would like to spawn a random tower with factory settings.

**Comment by Alan19** [comment]
Does `/roguelike dungeon here` work? If you don't have any custom dungeons, it should spawn a random tower.

**Comment by Skabbety** [comment]
Nope that doesn't work. Btw I changed the Config Settings and I didn't put anything in the Settings Folder

**Comment by Skabbety** [comment]
> Does /roguelike dungeon here work? If you don't have any custom dungeons, it should spawn a random tower.

Nope that doesn't work. Btw I changed the Config Settings and I didn't put anything in the Settings Folder

**Comment by Alan19** [comment]
What changes did you make to the configs?

**Comment by Skabbety** [comment]
> What changes did you make to the configs?

These are the changes : 

dimensionBL=
dimensionWL=0
doBuiltinSpawn=true
doNaturalSpawn=true
encase=true
furniture=true
generous=true
looting=0.085
lowerLimit=60
preciousBlocks=true
random=false
rogueSpawners=true
spawnChance=1.0
spawnFrequency=37
upperLimit=100

**Comment by srwaggon** [comment]
@Skabbety What sorts of problems are you facing? And which version of the mod are you using?

Try this:
`/roguelike dungeon here builtin:desert`

If this does not yield a default dungeon that is satisfying, please tell me what console says after the command fails.
