### ISSUE TITLE
Can't use loot tables in custom loot json

### ISSUE THREAD

**Issue by RedBlockCreator** [Greymerk/minecraft-roguelike#211]
Following the tut and overriding all default loot tables with the minecraft:chests/simple_dungeon or any other loot table simply doesn't work, and it keeps pulling from the builtin no matter what I do. I have followed the demo.

loot_all.json
{
"name": "test:loot_all",
"loot_rules": [
{
"level" : [0, 1, 2, 3, 4],
"type" : [
"STARTER", "FOOD", "POTIONS", "MUSIC", "SUPPLIES", "SMITH", "BREWING", "WEAPONS", "ARMOUR", "ENCHANTING"
],
"table": "minecraft:chests/simple_dungeon",
"each" : true
}
]
}

loot.json
{
"name" : "builtin:loot",
"inherit" : [
"test:loot_all"
]
}

I have tried every variation i can think of and I and a couple other people at this point are simply at a loss.

**Comment by Oblivionized** [comment]
I'm also having this issue, super frustrating! I really want it to work though, maybe if we went back a few builds then it would work again?

**Comment by srwaggon** [comment]
@RedBlockCreator 
@Oblivionized 

If you want to use vanilla loot tables to insert modded loot, try these formattings, check out my configuration as an example:


loot_all.json
```json
{
  "name": "test:loot_all",
  "loot_rules": [
    {
      "level" : [0, 1, 2, 3, 4],
      "type" : [
        "STARTER", "FOOD", "POTIONS", "MUSIC", "SUPPLIES", "SMITH", "BREWING", "WEAPONS", "ARMOUR", "ENCHANTING"
      ],
      "table": "minecraft:chests/simple_dungeon",
      "each" : true
    }
  ]
}
```
loot.json
```json
{
  "name" : "builtin:loot",
  "inherit" : [
    "test:loot_all"
  ]
}
```
