### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by k1xy** [Greymerk/minecraft-roguelike#212]
good morning, I've promblem with server. I was looking for dungeon and then server is shutting down. and now, when im connecting, server is kicking me and shutting dow

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks_1.64_dev.jar)
  PhosphorFMLLoadingPlugin (phosphor_1.12.2_0.2.4build46_universal.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  HCASM (HammerCore-1.12.2-2.0.5.0.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 4/21/20 8:10 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at com.inventorypets.worldgen.WorldGenTreeTop.func_180709_b(WorldGenTreeTop.java:57)
	at com.inventorypets.worldgen.WorldGenInventoryPets.generateOverworldDungeons(WorldGenInventoryPets.java:72)
	at com.inventorypets.worldgen.WorldGenInventoryPets.generate(WorldGenInventoryPets.java:21)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.18.0-147.5.1.el8_1.x86_64
	Java Version: 1.8.0_242, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 810922768 bytes (773 MB) / 2036858880 bytes (1942 MB) up to 2036858880 bytes (1942 MB)
	JVM Flags: 2 total; -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                      | Source                                         | Signature                                |
	|:------ |:------------------- |:---------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                       | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                 | 9.42                         | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                    | server.jar                                     | None                                     |
	| LCHIJA | forge               | 14.23.5.2847                 | server.jar                                     | None                                     |
	| LCHIJA | damageindicatorsmod | 1.0                          | 1.12.2DamageIndicatorsMod_3.5.1.jar            | None                                     |
	| LCHIJA | jei                 | 4.15.0.293                   | jei_1.12.2_4.15.0.293.jar                      | None                                     |
	| LCHIJA | abyssalcraft        | 1.9.17                       | AbyssalCraft_1.12.2_1.9.17.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | baubles             | 1.5.2                        | Baubles_1.12_1.5.2.jar                         | None                                     |
	| LCHIJA | cyclicmagic         | 1.19.20                      | Cyclic_1.12.2_1.19.21.jar                      | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHIJA | guideapi            | 1.12-2.1.8-63                | Guide-API-1.12-2.1.8-63.jar                    | None                                     |
	| LCHIJA | bloodmagic          | 1.12.2-2.4.3-105             | BloodMagic-1.12.2-2.4.3-105.jar                | None                                     |
	| LCHIJA | bookshelf           | 2.3.590                      | Bookshelf_1.12.2_2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | cavern              | 2.1.9                        | Cavern_1.12.2_v2.1.9.jar                       | b78e30ad27c82f3e348f76edf497058678207299 |
	| LCHIJA | cucumber            | 1.1.2                        | Cucumber-1.12.2-1.1.2.jar                      | None                                     |
	| LCHIJA | cxlibrary           | 1.6.1                        | cxlibrary-1.12.1-1.6.1.jar                     | None                                     |
	| LCHIJA | harvestchevsky      | b1                           | gentleharvest_1.12_b1.jar                      | None                                     |
	| LCHIJA | gottschcore         | 1.12.1                       | GottschCore-mc1.12.2-f14.23.5.2768-v1.12.1.jar | None                                     |
	| LCHIJA | hammercore          | 2.0.5.0                      | HammerCore-1.12.2-2.0.5.0.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | waila               | 1.8.26                       | Hwyla_1.8.26_B41_1.12.2.jar                    | None                                     |
	| LCHIJA | improvableskills    | 65r                          | ImprovableSkills-1.12.2-65r.jar                | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | ic2                 | 2.8.189-ex112                | industrialcraft_2_2.8.189_ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | inventorypets       | 2.0.2                        | inventorypets_1.12_2.0.2.jar                   | None                                     |
	| LCHIJA | inventorytweaks     | 1.64-dev+release.123.f374f4b | InventoryTweaks_1.64_dev.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks       | 1.12.2-3.0.8-12              | IronBackpacks_1.12.2_3.0.8_12.jar              | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844            | ironchest_1.12.2_7.0.67.844.jar                | None                                     |
	| LCHIJA | mantle              | 1.12-1.3.3.55                | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCHIJA | targeting_api       | 0.15                         | targeting_api-0.15.jar                         | None                                     |
	| LCHIJA | mkultra             | 0.99.12                      | MKUltra-0.99.12.jar                            | None                                     |
	| LCHIJA | morefurnaces        | 1.10.4                       | MoreFurnaces-1.12.2-1.10.4.jar                 | None                                     |
	| LCHIJA | msmlegacy           | @VERSION@                    | MoreSwordsLegacy_1.12.2_1.0.4.jar              | None                                     |
	| LCHIJA | mysticalagriculture | 1.7.0                        | MysticalAgriculture-1.12.2-1.7.0.jar           | None                                     |
	| LCHIJA | patchouli           | 1.0-20                       | Patchouli_1.12.2_1.0_20.jar                    | None                                     |
	| LCHIJA | quickleafdecay      | 1.2.4                        | QuickLeafDecay_MC1.12.1_1.2.4.jar              | None                                     |
	| LCHIJA | rustic              | 1.1.2                        | rustic_1.12.2_1.1.2.jar                        | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.13.0.179            | TConstruct-1.12.2-2.13.0.179.jar               | None                                     |
	| LCHIJA | treasure2           | 1.10.0                       | Treasure2-mc1.12.2-f14.23.5.2768-v1.10.0.jar   | None                                     |
	| LCHIJA | treechopper         | 1.2.4                        | TreeChopper_1.12.2_1.2.4.jar                   | None                                     |
	| LCHIJA | phosphor-lighting   | 1.12.2-0.2.4                 | phosphor_1.12.2_0.2.4build46_universal.jar     | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks_1.64_dev.jar)
  invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor_1.12.2_0.2.4build46_universal.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
HCASM (HammerCore-1.12.2-2.0.5.0.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 712 names; 917 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @65r

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 10; [EntityPlayerMP['k1xy'/293, l='world', x=1793.29, y=65.84, z=-615.89]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by k1xy** [comment]
sry, wrong theme

**Comment by Gunner76th** [comment]
One thing of note I see on this crash report, you are running a Minecraft 1.12.2 modpack, but have only allocated 2 gigs of ram. 1.12.2 modpacks needs at least 4 gigs of ram otherwise you will eventually encounter an out of ram Java Heap error.
