### ISSUE TITLE
Cascading Lag

### ISSUE THREAD

**Issue by Tombstone1973** [Greymerk/minecraft-roguelike#214]
29.06 03:50:59 [Server] WARN Roguelike Dungeons loaded a new chunk [-136, 26] in dimension 0 (overworld) while populating chunk [-135, 25], causing cascading worldgen lag.
29.06 03:50:59 [Server] WARN Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Probably nothing you can do about this, but I figure I'd just put it here in case there is a fix for it. The mod pack I am using seems to be pretty chonky for no real reason when loading chunks. And it seems to be because of mods doing this.

**Comment by FishInABukkit** [comment]
This is due to the way that forge handles chunk generation, AFAIK there is nothing you can do as a player. A possible fix is to check your logs and look to see if the overflow is caused by another mod conflicting with Roguelike, for me it was TAIGA. Hope this helps!
