### ISSUE TITLE
Hearts set to 0

### ISSUE THREAD

**Issue by Sunokami** [Greymerk/minecraft-roguelike#216]
Hi, I have a big problem. Since I entered the twilight dimension my heart have been set to 0 no matter what I do. I tried to eat diverse food, use some hearts (I loose them when I die, a little each time). It's litteraly unplayable. I lost all my stuff (no grave anywhere) because of this and I'm at the edge of definitly stop playing this mod.

**Comment by bbharier** [comment]
@Sunokami did you ever figure out what caused this? Was it from this mod or another mod that was causing a conflict?
