### ISSUE TITLE
Special jungle dungeon road goes out infinitely in skyblock-type world

### ISSUE THREAD

**Issue by elderpyre** [Greymerk/minecraft-roguelike#22]
I'm using Roguelike dungeons with the Fun World Gen mod (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3) using its Sky Dimension world type, and upon coming across one of the special jungle dungeons from RLD, the path leading to it seems to go out infinitely from the dungeon entrance. On further inspection, this appears to be the case for any dungeon that has a path leading up to it, as demonstrated in the attached map screenshot.
![2015-06-21_19 13 11_test22_overworld_day](https://cloud.githubusercontent.com/assets/12993554/8274612/db2c29c2-1849-11e5-84c3-1f3d268c821a.png)

**Comment by Greymerk** [comment]
It's interesting that only happens to the east. That's a terrible bug though.

Guess going to have to see if I can figure it out.

**Comment by Greymerk** [comment]
The jungle temple has been completely redone for 1.4.
