### ISSUE TITLE
Config file changes order of settings

### ISSUE THREAD

**Issue by copygirl** [Greymerk/minecraft-roguelike#23]
I'm using git for a [project](https://github.com/copygirl/PackOPdater) and [modpack](https://github.com/copygirl/obsidian-Modpack) at the moment, and I noticed the Roguelike Dungeons config file changes every now and then. The generous and doNaturalSpawn settings are swapping, to be more exact. This is less of an issue and more of a tiny request, but if you could make the order of these settings be static, that would be useful for our git project.

(Sadly, once a file is tracked in git, you can't ignore changes anymore. There's a way, but it only works for a single local repository.)

**Comment by Greymerk** [comment]
I actually made that change in the 1.8 version a month ago. It had bothered me for a while as well.

https://github.com/Greymerk/minecraft-roguelike/commit/5bbf8121fa523b9d9371da6f7585bdaa91f07d2b

I hadn't planned on making further releases for 1.7 though, so this is for 1.8.

**Comment by copygirl** [comment]
Aww. Alright then, thanks!
