### ISSUE TITLE
[Version Port] 1.20.1 Fabric

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [Greymerk/minecraft-roguelike#236]
Title says everything

**Comment by Greymerk** [comment]
shouldn't be too difficult to create a port, but i'll wait until the next update.

can you explain why you need this? i'm just curious.

**Comment by HazeWorksOnFiveMServer** [comment]
I wanted to have roughlike dungeons in my vanilla + modpack but its on fabric 1.20.1

**Comment by Greymerk** [comment]
I'm thinking to publish a new version on Friday, so I'll plan to include a 1.20.1 version then as well.

**Comment by Greymerk** [comment]
https://modrinth.com/mod/roguelikedungeons/version/2.0.4beta-1.20.1-fabric

**Comment by AvrgDerk** [comment]
Adding to how insanely grateful I am to see you back and for porting this to 1.20.1 :'-) Longtime fan and ecstatic to have your mod installed again over dungeon crawl.

<3 Thank you greymerk, you inspired me heavily when I was younger and you're a big part of why I learned about nbt editing and mc modding.

**Comment by Greymerk** [comment]
@AvrgDerk Thanks for the message. Every time I solve some weird NBT puzzle to make a block or item generate properly I kind of hope someone will find the solution in my source code if they need to figure out the same thing.

PS: In case you didn't know, I made a Discord for comments/questions related to the mod.
[https://discord.gg/8pXfCG2vvm](https://discord.gg/8pXfCG2vvm)
