### ISSUE TITLE
Enchanted books generated as the contents of chiseled bookshelves are fake.

### ISSUE THREAD

**Issue by LeCaptainFlynn** [Greymerk/minecraft-roguelike#237]
On version 2.0.4beta-1.20.1-fabric. 
Books can't be used for enchanting, or anything really.

**Comment by Greymerk** [comment]
Oh wow.. jeez. I didn't notice that. Apparently this only affects the 1.20.1 port that I did. It's putting the enchant on the book item rather than creating an enchanted book ingredient.

**Comment by Greymerk** [comment]
I've fixed the issue and posted a new 1.20.1 version on modrinth. thanks for the heads up!
