### ISSUE TITLE
Compatibility with Sparse Structures. 1.21

### ISSUE THREAD

**Issue by makumaku1974** [Greymerk/minecraft-roguelike#238]
There is actually a massive problem with this mod. Somehow there are two Roguelike Dungeons a bit near to each other. Even with Sparse Structure installed.

![image](https://github.com/user-attachments/assets/0f93954f-129d-4edf-bcf8-aeba00812240)

**Comment by Greymerk** [comment]
While I agree that it'd be preferable for this to work, I'll have to look at the source code for sparse structures to see if it's even possible. My mod isn't technically a structure, it's more like a unique chunk feature pretending to be a structure.

**Comment by makumaku1974** [comment]
> While I agree that it'd be preferable for this to work, I'll have to look at the source code for sparse structures to see if it's even possible. My mod isn't technically a structure, it's more like a unique chunk feature pretending to be a structure.

oh i see, but I think it would be better if you set a config for it to be rare than relying with the sparse structure in that case.

**Comment by Greymerk** [comment]
I already figured out how to fix this and the fix works. I have some work to do to clean up the solution, but yeah. I just needed to pull the placements from the dynamic registries, which sparse structures hooks into.

Thanks for pointing this problem out.

**Comment by makumaku1974** [comment]
No problem glad to help. It was a bit rare though seeing two together, but if I had more structure mods. Roguelike Dungeons actually becomes rare but this time i only had battle towers which is a datapack and Roguelike dungeons.

**Comment by Greymerk** [comment]
I fixed this months ago. just closing the issue as complete. It was because I needed to reference the world id specifically in the serverstate objects, instead of just referencing the overworld.
