### ISSUE TITLE
How to set up the loot? Using Commands...

### ISSUE THREAD

**Issue by Tsyklop** [Greymerk/minecraft-roguelike#24]
I read the wiki but how to customize the file for loot I do not understand ...
Could you throw an example? Я создал папку "settings"... Но что делать дальше без понятия... 

and further. Regarding commands.

`/ roguelike dungeon X Z setting
where "setting" is the name of the setting you wish to spawn.`

that the setting for? where to get them ?

**Comment by phase5** [comment]
Hi,

Have another look on the wiki page for loot.  Greymerk has made some fantastic improvements to the whole loot side of things and if you look at the bottom of the wiki file, he has also provided an excellent set of examples too.

It really is worth another look.

**Comment by phase5** [comment]
Oh, sorry.   Your second question regarding the command.

When you create custom configurations in the settings folder - each one has a "name" element right at the top.   This is what he is referring to with "setting" I think.

For example, if you have at the top of your json file...

"name" : "test"

..then your command might look like..

/ roguelike dungeon 100 200 test

This would create a dungeon at x=100, y=200, using settings from your file that had at the top the "name" : "test".

Hope that helps a little.

**Comment by Greymerk** [comment]
As stated above, I've overhauled the whole system, updated the documentation, and provided new example code. Hopefully this helps.
