### ISSUE TITLE
Issue with disabled Mystical Agriculture crops being spawned on farmland in upper floors of dungeons

### ISSUE THREAD

**Issue by jhansen69** [Greymerk/minecraft-roguelike#240]
I'm doing some bug-fixing on a modpack that I released (https://www.curseforge.com/minecraft/modpacks/rongos-colonial-expedition) I'm noticing that some crops that have been disabled using the Mystical Customization addon mod from Blake (https://www.curseforge.com/minecraft/mc-mods/mystical-customization) are still being spawned on the farmland blocks that are present in some of the room that have the 2 corners with redstone blocks & lamps.

I noticed this with a crop that was explicity marked as disabled (uranium) and with a crop that shouldn't have been activated at all (compressed iron which is dependent on the presence of PneumatiCraft). 

These crops are not available in game for crafting or spawning so I'm not sure where it's pulling that data from.

When the crops are broken, they drop seeds/essence for which there is no use/recipe.

I'm going to attempt to see if I can alter the harvest/break loot tables for these rogue crops as a stopgap. Might be a nice customization option to enable/disable modded crop planting on those farm blocks.

Otherwise, I along with millions of other Minecraft players, really enjoy your mod! Keep up the amazing work.

**Comment by Greymerk** [comment]
Just reviewing my open issues, which I haven't done in a bit. I'm not sure what's going on here, but it sounds like shenanigans from another mod that's interfering with block placement.

I really am not maintaining the 1.12 version of this mod anymore so i can't comment beyond that. It amazes me that people still play 1.12, i'm so out of the loop in modding i guess. Sometimes I wonder if I shouldn't rewrite the 1.12 version just to bring it in line with the 1.21 version.

Sorry again for falling behind on reading these.
