### ISSUE TITLE
No special drops (trimmed armor and tools)

### ISSUE THREAD

**Issue by wh0oo** [Greymerk/minecraft-roguelike#242]
Hello!

Ive installed the latest version and tested in a single player local instance with only this mod, and no special drops are occuring.

Here is my config online:
{
  "mob_drops": true,
  "frequency": 1.0,
  "debug": true,
  "rooms_per_level": 20,
  "roguelike_loot": true
}

Here is the local config:
{
  "mob_drops": true,
  "frequency": 1.0,
  "debug": false,
  "rooms_per_level": 20,
  "roguelike_loot": true
}

Let me know if you need anything else, though I think this is repeatable.

**Comment by wh0oo** [comment]
Ugh, okay, so ive been playing for a 45 mins killing mobs, and I can now say that 2 helmets dropped.  So i stand corrected, there are drops I guess. They are just VERY VERY VERY rare.  Way too rare. :/

**Comment by Greymerk** [comment]
This is fixed. it was due to a change mojang made to default values for mob equipment
