### ISSUE TITLE
Feature Request: Change spawned mobs via config

### ISSUE THREAD

**Issue by Teibidh** [Greymerk/minecraft-roguelike#25]
I'm sure that somewhere in the code there is an array or collection of entity IDs to assign to spawners as they are generated. It would be radical (in fact, it would be the only thing I think this mod is "missing", though I will certainly still use it in all my worlds regardless) if that list could be populated from the config file, allowing Entity IDs from other mods to be utilized.

At some point I will take a look at the source code and maybe do a pull request, but I would have to learn Java (I'm a mediocre C# guy as it stands.) and we might all be better off if it was done by someone with a clue. :)

**Comment by Greymerk** [comment]
This has been an undocumented feature for a long time actually. It had some bugs, but will be fixed in 1.4.2 and will be documented in the wiki.
