### ISSUE TITLE
Loot

### ISSUE THREAD

**Issue by whitewolfxs** [Greymerk/minecraft-roguelike#27]
i have been for a couple hours now trying to understand how loot customization works (im kinda new to programming ) i was wondering if u could set up a example like u got for the structure section or maybe if somebody could help me with geting how to costumize the loot

**Comment by Greymerk** [comment]
What are you trying to do? I could try to make an example that suits your need.

**Comment by whitewolfxs** [comment]
im trying to change the loot that spawns in chest so that includes more mod items and other random minecraft items

**Comment by Greymerk** [comment]
I've been pushing hard toward a new version of the mod, and a 1.7/1.8 new release. I wound up working on the loot system and overhauling it dramatically. If you're able to wait on this I should be able to make it way simpler to configure than it currently is.

Right now you can only reconfigure loot categories for what gets randomly put in chests. But with some of the new changes you'll actually be able to do things like put exact N amount of some item on a particular level, or anywhere in the dungeon. This might be useful for what you're doing.

**Comment by whitewolfxs** [comment]
how long ? if i may ask.. im trying to make a fun modpack for my friends and stuff i would like it to have it running by 15 december but without this it will be kinda hard :p but yeah.
but yeah sure i can wait just would like to know how long

**Comment by Greymerk** [comment]
Tonight or tomorrow maybe. Things are getting close to done.

**Comment by whitewolfxs** [comment]
i was wondering if your going to update the wiki for "Loot Customisation" since could be helpfull for what im trying to do since i still trying to understand how to create a loot table.

**Comment by Greymerk** [comment]
At the moment I'm just trying to build a demo loot setting. It's complicated because tiny mistakes are hard to track down.

**Comment by whitewolfxs** [comment]
ok :) thx alot for everything u have done

**Comment by Greymerk** [comment]
I attached the demo i made on the release page
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.4

Just create directory config/roguelike_dungeons/settings and unpack those text files in. These settings fully replace the loot system with custom loot. In order to use modded items you need use whatever name you'd normally invoke with the give command.

I'll update the wiki later on. This loot config stuff is giving me a headache. This is by far the most difficult thing to configure.

**Comment by Greymerk** [comment]
There was apparently a bug in 1.4. Try the 1.4.1 version. The attached loot settings are also much easier to understand.

One thing that there is yet to do is provide better error reporting. It's sometimes very mysterious why a setting fails.
