### ISSUE TITLE
[REQUEST] Customization can change tower

### ISSUE THREAD

**Issue by Haggle1996** [Greymerk/minecraft-roguelike#30]
I've had a lot of fun customizing my dungeons underground, particularly making some awesome looking bunkers. However, the medieval tower that spawns on the surface would look real cool if I could change it as well.

Give you an idea of what I've done with your dungeons: http://i.imgur.com/ZZsIkQt.png

**Comment by Greymerk** [comment]
First of all, glad you're having fun!

You can change the tower. It has its own tower type and theme property.
{
"tower" : {
  "type" : "ROGUE",
  "theme" : (a theme definition similar to how level themes are defined)
}

available towers at the moment are:
ROGUE, ENIKO, ETHO, PYRAMID, JUNGLE, WITCH, HOUSE

the etho tower (as in ethoslab) is death games. the eniko tower is the one you'll usually see in mountain areas.

**Comment by Haggle1996** [comment]
That is awesome! Thank you so much for the mod and response!
