### ISSUE TITLE
STRIPES and CHECKERS produce the same result

### ISSUE THREAD

**Issue by Haggle1996** [Greymerk/minecraft-roguelike#31]
Both customization options for STRIPES and CHECKERS seem to produce the same pattern. It would be nice if STRIPES did alternating horizontal strips while CHECKERS did alternating diagonal stripes.

**Comment by Greymerk** [comment]
The difference between checkers and stripes is that you can add more than two blocks to stripes. But that's a good suggestions. I had made checkers before making stripes and just left things the way they were.

**Comment by Greymerk** [comment]
I've added in "LAYERS" and "COLUMNS" as new block provider options. You can probably guess what they do. I'm going to leave stripes and checkers the way they are because stripes is still needed for 3D diagonal stripes. And Checkers is kind of a legacy thing now.

**Comment by Haggle1996** [comment]
Very awesome! Thank you.
