### ISSUE TITLE
1.4.1 loot

### ISSUE THREAD

**Issue by foxanthony1** [Greymerk/minecraft-roguelike#32]
I updated to 1.4.1, created a roguelike_dungeons/settings folder, got the latest loot-settings-demo.zip and put the files into that folder.

Just to be sure I noticed a change, I edited _loot_all_levels.json with "Name" : {"type" : "STRING", "value" : "What's this?"}, replacing "Surplus Pantaloons" and in _loot_level0.json I changed all the food ids to "snowball". I'm not seeing any changes.

I tried this in both 1.7.10 (my own custom pack) and 1.8 (FTB Unstable).

Really glad you're working on this, not just for my pack, but it will be nice to play other people's packs and see loot that fits the pack.

**Comment by Greymerk** [comment]
First of all, just want to say i'm glad you're trying out the settings. This is a feature I'd really like to get right.

Anyway, I tried making the changes you described in a forge instance with only roguelike dungeons and it worked. Then i loaded up FTB unstable using the FTB launcher, replaced roguelike dungeons with 1.4.1, and copied my settings directory into the config/roguelike_dungeons directory and tried it. The settings changes worked there as well. "What's this?" pants spawned in the starter chest, and the chest in the cake room was full of snowballs.

Try manually spawning a dungeon using command "/roguelike dungeon here loot" and see if it spits back an error.

**Comment by foxanthony1** [comment]
Whew! I was using "/roguelike dungeon [x] [y]" to spawn dungeons for testing. I just checked a naturally spawned dungeon and it was immediately obvious that the loot was different.

Thank you so very much! This mod has always been cool, but this takes it to another level. You might consider bumping the version number to 2.0 with all the changes you've made recently. Great work!

**Comment by Greymerk** [comment]
i updated the [commands](https://github.com/Greymerk/minecraft-roguelike/wiki/Commands) page on the wiki with more information about what you can do.

The command with specified settings is the only way to get "abstract" settings without a criteria to spawn. This can be useful for testing.

**Comment by foxanthony1** [comment]
Nice. I made a video showing people how to add/change loot and posted it on the forum.
