### ISSUE TITLE
(Q) chance temple theme pick rate

### ISSUE THREAD

**Issue by Ezoteric** [Greymerk/minecraft-roguelike#33]
Hey man love this mod but where can i change the chance of a non tower to spawn in its theme biome.

I want more temples and witchhuts etc and less normal towers :P 

Could make it a option or just tell how to edit and i compile myself ;) 

Thnx in advance

**Comment by Greymerk** [comment]
Change these to what you want:
https://github.com/Greymerk/minecraft-roguelike/blob/master/src/main/java/greymerk/roguelike/dungeon/settings/builtin/SettingsGrasslandTheme.java#L32

https://github.com/Greymerk/minecraft-roguelike/blob/master/src/main/java/greymerk/roguelike/dungeon/settings/builtin/SettingsTheme.java#L13

If you want randomization you'll need to add multiple settings with weighted criteria. The system isn't setup for randomly selected towers within the same dungeon settings.

**Comment by Ezoteric** [comment]
Thnx for the fast reply. 
Ok so tower rogue is the standard tower and I change rogue to witch for example?

**Comment by Greymerk** [comment]
Yeah, any of the enum constants in: https://github.com/Greymerk/minecraft-roguelike/blob/master/src/main/java/greymerk/roguelike/dungeon/towers/Tower.java#L14
