### ISSUE TITLE
Towers spawn adjacent to each other.

### ISSUE THREAD

**Issue by Haggle1996** [Greymerk/minecraft-roguelike#34]
This just started happening when I grabbed 1.4.2-1.7.10: dungeon towers are now occasionally spawning within 1 chunk of each other, overlapping each others' dungeon. Not sure what's happening, but I've seen several of these in randomly generated worlds since yesterday and never before with the version of Roguelike on curseforge.

**Comment by Greymerk** [comment]
what seed? this is possible by the way. nothing special has change with regard to selecting spawn locations.

**Comment by Haggle1996** [comment]
If it's possible, then no worries. Guess I've just been lucky and never seen it happen before.

**Comment by Greymerk** [comment]
It can happen, it's just rare. I don't mind that it happens because it creates chaotic dungeons that are interesting in their own way. Conjoined dungeons are something you could consider a lucky find. I've personally never seen two dungeons spawn right next to eachother one chunk apart.
