### ISSUE TITLE
catacomb Crash

### ISSUE THREAD

**Issue by vagaprime** [Greymerk/minecraft-roguelike#35]
Created a new world and crashed right away.

http://pastebin.com/62ma3bVc

**Comment by Greymerk** [comment]
can you tell me what seed? I have made hundreds of test worlds and never seen this happen.

**Comment by vagaprime** [comment]
I let minecraft pick the seed and it crashed everytime I tried to load the world. I never even got into the world after creating it. It was using my modpack.

here is the list of mods
https://docs.google.com/spreadsheets/d/13WVyKMBs3wSDexM8u18fbpin77VEwHLOjXdLmtoNsRU/edit#gid=1084658620

**Comment by Greymerk** [comment]
Alright. Well.. I have no idea why that would happen, it looks like a bug deep in the internals of minecraft that's being triggered by something beyond my control. I can catch the exception and see if that fixes the problem for you. No idea why that's happening though. I have seen this bug reported however. I have never seen it happen in all the time i've been developing the mod.

**Comment by Greymerk** [comment]
Try this version
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.4.4-pre1

**Comment by vagaprime** [comment]
Downloading it now. I will let you know what happens.

**Comment by vagaprime** [comment]
Just created a new world with that same seed since I deleted the first one. I was able to get the cords for the dungeon from the log and teleported to the site after loading into the world with our problem and did not crash.

**Comment by Greymerk** [comment]
Cool. Also this is a much newer version than the one you had before. A bunch of changes and fixes have been made since then. You may notice some differences.

**Comment by vagaprime** [comment]
Cool. I can not wait to play around with this version. The one I have been using is the version posted on curseforge,

**Comment by vagaprime** [comment]
Looks like the world gen cash is back again.

https://github.com/MageTech-gate/Release/issues/6
