### ISSUE TITLE
disabling the new forest house tower

### ISSUE THREAD

**Issue by Fabboz** [Greymerk/minecraft-roguelike#36]
Hi,
I want to know if is possible to disable the new forest house tower... because is too similar at my own house that i build in my games.
Or may you make something like an hole in the roof or use a decayed style (something to change how it look in journeymap)?

thx bye

**Comment by Greymerk** [comment]
create a setting file such as config/roguelike/settings/forest.json

inside put:

```javascript
{
	"name" : "forest",
	"criteria" : {
		"biomeTypes" : [
			"FOREST"
			]
	},
	"tower" : {
		"type" : "ROGUE",
		"theme" : {
			"base" : "TOWER"
		}
	}
}
```

This should change all forest dungeons back to using the normal tower.

**Comment by Fabboz** [comment]
Thx, works perfect.

2016-01-04 22:05 GMT+01:00 Brian Rivas <notifications@github.com>:
