### ISSUE TITLE
Added custom loot but now only get default towers

### ISSUE THREAD

**Issue by phase5** [Greymerk/minecraft-roguelike#37]
First of all, absolutely fantastic work!

I am having something strange happen and cannot understand why.  (Probably me doing it wrong!)

I set up your mod (had used it before) and immediately noticed that there are now nicely themed towers in different biomes.  very very nice.  (I have seen a brick house in woodland, a sandstone tower in desert and a few others)

However, I then add custom loot.  I simply took your demo files from the bottom of the loot customisation page, added a few extra items into the all levels file and tried it out.

The loot appears to work just fine.  The problem I am seeing is that with those files in place, I seem to only ever get the original default towers.

Is it possible for me to both add some custom loots, but otherwise not disturb the other configs?  (so I can keep all the pretty towers/houses)

**Comment by phase5** [comment]
Err, sorry - should have mentioned:

roguelike-1.7.10-1.4.4

**Comment by Greymerk** [comment]
At the moment, if you specify a setting that replaces one of the built-in dungeons then it'll reset everything to defaults. Meaning you need to rebuild the biome themed dungeon from the ground up. Being able to specify what to override in your dungeon settings is a feature I plan on adding eventually.

**Comment by phase5** [comment]
Thanks very much for the prompt response.

Sorry to repeat, but just so I understand it right...   What you are saying is that there is no way for me to add custom loot without losing all the nice towers and things, unless I were to recreate them all in the JSON?

I did try without the override option set (so it would add to existing loot instead of replacing according to docs) but that didn't seem to help.

If that's correct then I might try adding to the DungeonLoot table as you conveniently mentioned in another thread that you use the Forge hook or something.  I assume that means if I add to the normal DungeonLoot table, it will get added to rogue chests.

That will do for the time being and give me time to get to work on replicating all the towers/dungeons in JSON.

I would like to help you if there is anything I can do that would be useful.
While I do know quite a few languages - unfortunately, Java is not one of them.
Would you like help with maybe expanding the documentation?  From my own experience of using it, I think more examples at the very least would help a lot.

**Comment by Greymerk** [comment]
Correct. The settings were originally create with the idea that they'd be used mostly for themes. This notion of adding loot is relatively recent so it'll need a bit more work to separate it out.

The plan is to allow a Dungeon Setting to specify Settings Types to override. That way there's more control in place as to what exactly is being changed. The types are already defined here:
https://github.com/Greymerk/minecraft-roguelike/blob/master/src/main/java/greymerk/roguelike/dungeon/settings/SettingsType.java

It'll probably be a couple weeks or so until i get around to this as i'm in the middle of working on a bunch of other stuff.

**Comment by TheDeviantCrafter** [comment]
Has this issue been resolved? Changing loot would be a very powerful tool for modpack makers.

Alternatively, would it be possible for someone to re-create each of the roguelike dungeons on JSON format so we can edit the chests contents that way?

**Comment by Greymerk** [comment]
No, i've not resolved this issue. It's a design problem that i've not worked out yet.

I'm trying to work it out now that the 1.9 transition has happened and i've worked out the bugs with the existing system.

the design problem is how to create a system that would allow someone to add loot, replace the whole loot system, and make changes based on criteria. Like for instance adding extra gold to chests in jungle dungeons, but also adding more coal to chests in every sort of dungeon.

I'd like to end up with a format that allows for such flexibility, in an extensible way.

**Comment by TheDeviantCrafter** [comment]
Glad to hear the issue is being worked on. It's an amazingly powerful tool for modpacks to use, but currently it's not practical.

I'll look forward to using this. Hopefully it will become more widely adopted - loot that works in vanilla isn't as valuable in, say, a large tech pack.

**Comment by Greymerk** [comment]
Give this a try if you're still interested in this issue
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.5.1

I changed how settings work so that they mix with the built in settings. I haven't experimented extensively with the ramifications of this change, but it may suit the way most people want to use it.

**Comment by phase5** [comment]
Hi Greymerk.  Thank you very much for taking the time to look at this.  I must have missed the notification from your last message!

I have not looked at this yet but I will look and try it out.  Just wanted to respond so you didnt think you had done it for nothing.

Really appreciate you putting the time in.
