### ISSUE TITLE
plugin.yml

### ISSUE THREAD

**Issue by gschreiner83** [Greymerk/minecraft-roguelike#38]
Hello,
My server (omgserv) need the plugin.yml file to load the plugin.
I tried to add on, but, i'm unable to fill the "main" information.

How to create a plugin.yml file : http://wiki.bukkit.org/Plugin_YAML

Maybe this file could be added in every jar after that :)

**plugin.yml content :**

>name: Roguelike Dungeons
>main: ????
>version: "1.4.4"
>description: Adds randomized dungeons to the world.
>author: Greymerk
>website: http://github.com/Greymerk/minecraft-roguelike

**Comment by Greymerk** [comment]
"Points to the class that extends JavaPlugin"

There is no such class. I'll look into making one.

**Comment by gschreiner83** [comment]
Hello,
What are the news :) ?

**Comment by Bennyboy1695** [comment]
Why is a plugin.yml needed ? this is a forge mod not a bukkit plugin :P they are two completely different things, you clearly have a plugin thats missing its plugin.yml or are trying to install this as a plugin rather then a mod

**Comment by Greymerk** [comment]
Thanks for clarifying that, i'm not at all familiar with how bukkit works.
