### ISSUE TITLE
Spawning custom setting tower on server.

### ISSUE THREAD

**Issue by mobro09** [Greymerk/minecraft-roguelike#41]
Hi,

I'm having trouble with using the config files I've set up in single player on a server world, everything spawns fine in a local game and json code checks out on JSONlint, but while attempting to force one to spawn on a server none of the config files can be read!

Any suggestions?

Thanks.

**Comment by mobro09** [comment]
To be more specific about the issue, I have a Settings folder with custom tower settings based around your demo settings zip file. In a local game the files allow my tower to be both spawned via command and naturally in the world but on the server for some reason it says Failed: main not found.

Would there be another location the folder needs to be?

**Comment by Greymerk** [comment]
Nope, it should be your config dir, where roguelike.cfg appears that you place the settings directory. It could have something to do with the file encoding if you're moving files from windows to linux.

**Comment by Greymerk** [comment]
Also don't forget that directories in linux (as with most things) are case sensitive.

**Comment by mobro09** [comment]
I got it! It was the settings folder on the dedi server, it had a capital letter.

Thanks for the advice!
