### ISSUE TITLE
Server crash on 1.8.9

### ISSUE THREAD

**Issue by kwpugh** [Greymerk/minecraft-roguelike#45]
crash report: http://pastebin.com/raw/X327VVF3

using:
forge-1.8.9-11.15.1.1764
RoguelikeDungeons-1.8.9-1.4.5.jar

**Comment by tyler489** [comment]
there should be an elderrich alter from thaumcraft around here
 (1351,73,-410), Chunk: (at 7,4,6 in 84,-26; contains blocks 1344,0,-416 to 1359,255,-401), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
i think the dungeon is trying to generate ontop of it if i had to make a guess

**Comment by Greymerk** [comment]
it looks like in the 1.8 version there's no check to make sure that the fetched tile-entity is a mob spawner. I added the check in the 1.9 version at some point.
