### ISSUE TITLE
Dungeons spawning in the nether

### ISSUE THREAD

**Issue by chrisbecke** [Greymerk/minecraft-roguelike#46]
Roguelike dungeons are spawning in the nether. Amusingly the towers are placed above the upper bedrock providing egress for the players on my server.

**Comment by Greymerk** [comment]
So as it turns out I forgot to whitelist the overworld explicitly last time i messed with how these work. 

Setting dimensionWL=0 should make things work as usual. I'll have to update the defaults.

**Comment by Greymerk** [comment]
Fix included in v1.5.0.
