### ISSUE TITLE
How to build? (Trying to get 1.9 version)

### ISSUE THREAD

**Issue by cemerson** [Greymerk/minecraft-roguelike#47]
Hey can someone explain how to build the source here (or point me to where docs on that can be found)? I'm trying to get this (awesome) mod working in 1.9.

**Comment by Drakkett** [comment]
Try the dev notes in the wiki.  That's where I started.   

Good luck,

Drakkett

**Comment by cemerson** [comment]
Thanks @Drakkett  - that got me close (I think)! Going to post a test build in the MCF thread to see if anyone can confirm it's built/working ok or not ... obviously an UNOFFICIAL build as I'm a total hack here w/my Eclipse setup. Thank you sir.

**Comment by Greymerk** [comment]
I haven't bothered to create a build for 1.9 because I figure in a week or two we'll be getting 1.9.2 or something. You can clone the project and just run the gradlew decomp routine just like you would for forge normally, and then gradlew build. There's nothing special here.

**Comment by cemerson** [comment]
Thanks @Greymerk - you're probably right about that ... thought I already saw something like 1.9.2 or something like that. FWIW ... I am a (C#) web dev by trade but am a TOTAL noob to the Minecraft modding world so I was just barely able to get Eclipse setup and finally got this to build. Anyhow I'll close this out since [my temporary build](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290238-roguelike-dungeons-v1-4-5?comment=1287) seems to be working.

**Comment by Greymerk** [comment]
Familiarize yourself with the processes outlined here:
http://www.minecraftforge.net/forum/index.php?topic=14048.0

setting up a dev environment for a mod that includes gradle should involve similar steps.

**Comment by cemerson** [comment]
Thanks Greymark - I'll take a look. Honestly Eclipse kinda grosses me out ... if someone would make a tutorial on getting Sublime Text setup for MC mod dev then I'd be all up in that! :) Fortunately for this situation I got in, got a build and got out so I'm set for now.  That said at some point I'd love to show my kid how a mod is made so maybe I'll revisit things in the future. 

Thanks again - love your mod man!
