### ISSUE TITLE
[1.9 Pre] Got a crash, saw your name.

### ISSUE THREAD

**Issue by ArisenAnew** [Greymerk/minecraft-roguelike#50]
Not sure if I should report here, or..? This is the first time I've bothered reporting a crash. [Pastebin.](http://pastebin.com/w9uSjfSf)

Crash happened when I tried to make a world. Sorry if I'm missing something; it's 3:51 and as I said, new at this. Anything else you need to see?

Edit: Oh, forgot to check closed issues. It's the Realistic Terrain Gen, isn't it? Apologies.
Edit2: Do I just need to remove one to play, or is there a workaround?

**Comment by Greymerk** [comment]
There's nothing I can do about it, so yeah, for now you'll just have to remove one or the other.
