### ISSUE TITLE
1.9 Issue with getting type for biome with realistic terrain gen

### ISSUE THREAD

**Issue by MCEventHorizon** [Greymerk/minecraft-roguelike#51]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 4.5.16. 14.22
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraftforge.common.BiomeDictionary.getTypesForBiome(BiomeDictionary.java:206)
	at greymerk.roguelike.dungeon.Dungeon.validLocation(Dungeon.java:154)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:59)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:138)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:113)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:998)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:971)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.access$800(AsynchronousExecutor.java:73)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:353)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1109515160 bytes (1058 MB) / 3092774912 bytes (2949 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.23 Powered by Forge 12.16.0.1878 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1878-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1878} [Minecraft Forge] (forge-1.9-12.16.0.1878-1.9.jar) 
	UCHIJAAAA	cei{1.1.1} [Chunk Edge Indicator] (1.9-chunkedgeindicator-1.1.1.jar) 
	UCHIJAAAA	actuallyadditions{1.9-r28} [Actually Additions] (ActuallyAdditions-1.9-r28.jar) 
	UCHIJAAAA	ArmorHud{2.0.1} [ArmorHud] (ArmorHud-1.8.9-2.0.1.jar) 
	UCHIJAAAA	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCHIJAAAA	bdlib{1.11.0.14} [BD Lib] (bdlib-1.11.0.14-mc1.9.jar) 
	UCHIJAAAA	BetterAchievements{0.2.2} [Better Achievements] (BetterAchievements-1.9-0.2.2.jar) 
	UCHIJAAAA	BBG{4.0.0} [BetterBedrockGen] (BetterBedrockGenerator-1.9.0-3.0.0.jar) 
	UCHIJAAAA	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCHIJAAAA	JEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
	UCHIJAAAA	blockdrops{1.0.0} [Block Drops] (Block Drops-1.9-1.0.0.jar) 
	UCHIJAAAA	BloodMagic{1.9-2.0.0-35} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-35.jar) 
	UCHIJAAAA	bookshelf{1.2.0.226} [Bookshelf] (Bookshelf-1.9-1.2.0.237.jar) 
	UCHIJAAAA	bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCHIJAAAA	mcmultipart{1.1.1} [MCMultiPart] (MCMultiPart-1.1.1-universal.jar) 
	UCHIJAAAA	chiselsandbits{9.15} [Chisels & Bits] (chiselsandbits-9.15.jar) 
	UCHIJAAAA	craftingtweaks{4.0.10} [Crafting Tweaks] (craftingtweaks-mc1.9-4.0.10.jar) 
	UCHIJAAAA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.9-2.0.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	UCHIJAAAA	DarkUtils{1.1.0.32} [Dark Utilities] (DarkUtilities-1.9-1.1.0.33.jar) 
	UCHIJAAAA	ElecCore{1.4.270} [ElecCore] (ElecCore-1.9-1.4.270.jar) 
	UCHIJAAAA	deepresonance{1.1.4beta30} [DeepResonance] (deepresonance-1.9.0-1.1.4beta30.jar) 
	UCHIJAAAA	dldungeonsjdg{1.8.11} [Doomlike Dungeons] (DoomlikeDungeons-1.8.11-MC1.9.jar) 
	UCHIJAAAA	enderbook{1.0.3} [Ender Book] (EnderBook-1.9-1.0.3.jar) 
	UCHIJAAAA	enderrift{0.15.0} [Ender-Rift] (EnderRift-1.9-0.15.0.jar) 
	UCHIJAAAA	enderutilities{0.5.2} [Ender Utilities] (enderutilities-1.9-0.5.2.jar) 
	UCHIJAAAA	ezstorage{1.0} [EZ Storage] (ezstorage-1.9-1.2.1.jar) 
	UCHIJAAAA	FFS{1.9-1.5.1.1.2} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9-1.5.1.1.2.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.9-v2.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.9-v2.2.jar) 
	UCHIJAAAA	substratum{1.3.0.0} [Substratum] (Substratum-1.9-1.3.0.0.jar) 
	UCHIJAAAA	foundry{2.0.0.0-alpha2} [Foundry] (Foundry-1.9-2.0.0.0-alpha2.jar) 
	UCHIJAAAA	advgenerators{0.9.20.8} [Advanced Generators] (generators-0.9.20.8-mc1.9.jar) 
	UCHIJAAAA	gravestone{1.2.4} [Gravestone] (Gravestone Mod 1.2.4 .jar) 
	UCHIJAAAA	inventorysorter{0.7.13+31} [Simple Inventory sorting] (inventorysorter-1.9-0.7.13+31.jar) 
	UCHIJAAAA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJAAAA	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.3} [Just Enough Resources] (JustEnoughResources-1.9-0.4.3.jar) 
	UCHIJAAAA	JET{1.2.28} [JustEnoughTooltips] (JustEnoughTooltips-1.9-1.2.28.jar) 
	UCHIJAAAA	jwin{univ_compat_filler} [Just What I Needed] (jwin-0.12.3.jar) 
	UCHIJAAAA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJAAAA	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.jar) 
	UCHIJAAAA	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCHIJAAAA	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.9.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-5.jar) 
	UCHIJAAAA	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCHIJAAAA	neotech{3.0.6} [NeoTech] (NeoTech-1.9-3.0.6.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9-3.0.6.jar) 
	UCHIJAAAA	notenoughwands{1.3.2} [Not Enough Wands] (notenoughwands-1.9.0-1.3.2.jar) 
	UCHIJAAAA	samsocean{1.0.0} [Classic Oceans] (OceanFloor-1.9-1.0.1.jar) 
	UCHIJAAAA	progressiveautomation{1.6.42} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.42.jar) 
	UCHIJAAAA	Psi{beta-31} [Psi] (Psi-beta-31.jar) 
	UCHIJAAAA	quantumflux{2.0.4} [QuantumFlux] (quantumflux-1.9-2.0.4.jar) 
	UCHIJAAAA	Quark{beta-18} [Quark] (Quark-beta-18.jar) 
	UCHIJAAAA	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UCHIJAAAA	reborncore{2.1.0.53} [RebornCore] (RebornCore-1.9-2.1.0.53-universal.jar) 
	UCHIJAAAA	redstonepaste{1.7.3} [Redstone Paste] (redstonepaste-mc1.9-1.7.3.jar) 
	UCHIJAAAA	xreliquary{1.9-1.3.1.322} [Reliquary] (Reliquary-1.9-1.3.1.322.jar) 
	UCHIJAAAA	ResourcefulCrops{1.9-1.3.1-47} [ResourcefulCrops] (ResourcefulCrops-1.9-1.3.1-47.jar) 
	UCHIJAAAA	ResourceLoader{1.5} [Resource Loader] (ResourceLoader-MC1.9-1.5.jar) 
	UCHIJAAAA	rftools{4.46} [RFTools] (rftools-1.9.0-4.46.jar) 
	UCHIJAAAA	rftoolsdim{4.23beta37} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta37.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCHIJAAAA	RTG{1.9-0.0.5} [Realistic Terrain Generation] (RTG-1.9-0.0.5.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.9.0.17} [Similsax Transtructors] (SimilsaxTranstructors-1.9.0.17.jar) 
	UCHIJAAAA	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UCHIJAAAA	techreborn{1.0.6.197} [TechReborn] (TechReborn-1.9-1.0.6.197-universal.jar) 
	UCHIJAAAA	VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	visiblearmorslots{1.1} [Visible Armor Slots] (VisibleArmorSlots[1.9]-1.1.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UCHIJAAAA	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9-2.2.0.186.jar) 
	UCHIJAAAA	wawla{2.2.0.178} [What Are We Looking At] (Wawla-1.9-2.2.0.186.jar) 
	UCHIJAAAA	YAFM{1.0.5} [Yet Another Food Mod] (yafm-1.0.5-mc1.9.jar) 
	UCHIJAAAA	YALSM{2.1.6} [Yet Another Leather Smelting Mod] (yalsm-2.1.6-mc1.9.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  net.fybertech.nwr.NowWithRendering
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (8) from ActuallyAdditions-1.9-r28.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
		* BetterAchievements|API (0.2.2) from BetterAchievements-1.9-0.2.2.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-35.jar
		* CapabilityCore|base (1.01) from EnderRift-1.9-0.15.0.jar
		* CapabilityCore|energy (1.01) from EnderRift-1.9-0.15.0.jar
		* CapabilityCore|tweakable (1.01) from EnderRift-1.9-0.15.0.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.15.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ActuallyAdditions-1.9-r28.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Fancy Fluid Storage-1.9-1.5.1.1.2.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CraftingTweaks|API (4.1) from craftingtweaks-mc1.9-4.0.10.jar
		* DLDungeonsAPI (1.1) from DoomlikeDungeons-1.8.11-MC1.9.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta30.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.270.jar
		* foundry.api (2.0.0.0) from Foundry-1.9-2.0.0.0-alpha2.jar
		* IC2API (1.0) from RebornCore-1.9-2.1.0.53-universal.jar
		* jeresources|API (0.4.3) from JustEnoughResources-1.9-0.4.3.jar
		* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.197.jar
		* McJtyLib (1.9.0-1.8.3) from mcjtylib-1.9.0-1.8.3.jar
		* PsiAPI (2) from Psi-beta-31.jar
		* reborncoreAPI (2.1.0.53) from RebornCore-1.9-2.1.0.53-universal.jar
		* ResourcefulCrops|API (1.9-1.3.1-47) from ResourcefulCrops-1.9-1.3.1-47.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* techrebornAPI (1.0.6.197) from TechReborn-1.9-1.0.6.197-universal.jar
		* VeinMinerApi (0.1) from VeinMiner-1.9_0.31.5.forgePost18010.jar
		* WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['DaneHD_'/378, l='New World', x=-49.11, y=151.23, z=265.76]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Greymerk** [comment]
The crash happened inside forge itself. probably due to either a bug in forge, or one of the core mods. I am not going to try to work around issues like this until 1.9 matures a bit.

**Comment by VladimirMangos** [comment]
I think this related similar biome related crashes in other mods when mods include

**Comment by Greymerk** [comment]
We determined it was likely a bug in their mod. There's specific conditions where a crash happens when using their world generator, but not without it. They are expecting this will be ironed out in their 1.9 rewrite.
