### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by MJRamon** [Greymerk/minecraft-roguelike#53]
This happens not every time, but happens.
Gen Type: Realistic Terrain Generation 1.9-2.0.0-alpha.3

http://pastebin.com/3hHEAGyT

**Comment by MJRamon** [comment]
Also, if the world was created, it seems that Roguelike has some problems with Realistic Terrain Generator and AbyssalCraft (without Roguelike there were no such errors)

http://pastebin.com/T4ALgZZx

**Comment by MJRamon** [comment]
Aaand also, while looking around the world, the game crashes sometimes

http://pastebin.com/QePH6RdZ

**Comment by MrRiegel** [comment]
ditto

**Comment by DrasticDemise** [comment]
Can confirm this crash using Realistic Terrain Generation and AbyssalCraft

**Comment by Greymerk** [comment]
Duplicate of #51

It's a bug related to the alpha version of RTG. They're planning a rewrite in which they hope to fix the issue.
