### ISSUE TITLE
Dungeons generating in all dimensions even though only 0 is whitelisted

### ISSUE THREAD

**Issue by RealGrep** [Greymerk/minecraft-roguelike#57]
I'm seeing dungeons in the nether, and the end (which obviously doesn't work well). However, the config file seems to only whitelist dimension 0. So there seems to be a bug there.

The config file generated on the server at config/roguelike_dungeons/roguelike.cfg, and contains the lines (among others):

dimensionBL=
dimensionWL=0

As far as I can see, they should only generate in the overworld, but I still get them everywhere.

This is in 1.9.4 with RoguelikeDungeons-1.9.4-1.5.2.jar and forge 1965.

Thank you :)

**Comment by oldjunyi** [comment]
I met the same issue in my server:
![dungeonintheend](https://cloud.githubusercontent.com/assets/641817/16150162/1e7e667c-34c8-11e6-834c-c01c983d24ef.png)

**Comment by RealGrep** [comment]
Thanks, will test it when I it's out. :)

**Comment by Greymerk** [comment]
Hopefully fixed in this update
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.5.3

**Comment by RealGrep** [comment]
I deleted the End and Nether and flew around for a good while, earlier. So far, so good. I think you got it. If I find any, I'll let you know, of course. I could have gotten super unlucky in my tests. Thanks for working on it! I appreciate it.

**Comment by RealGrep** [comment]
Just noticed this is still open. I've played a long time with it since then, and have not seen a single instance of the dungeons generating in the Nether or End. So I can conclusively say it's fixed. Closing. Thanks again!
