### ISSUE TITLE
Feasibility of using Minecraft's LootTables for Dungeons

### ISSUE THREAD

**Issue by gabizou** [Greymerk/minecraft-roguelike#58]
So, I understand that you've developed a sweet loot table customization aspect for your chests when generating the dungeons, but I'd find that Minecraft's own native loot tables would allow the chests to be generating loot only when opened, this way if a configuration is changed between restarts, the chests don't have to either be re-generated, etc. In some aspects, I'd imagine that the task of moving over to the native handling would be daunting, but I'd just be curious if that could still be feasible. 

Note: I'm not bashing or saying you're doing it wrong, but just to take advantage of the newer functionalities of the base game moving forward would probably help in future usage. I absolutely adore the mod for what it does already.

**Comment by Greymerk** [comment]
I have considered adding a configuration option to generate dungeons with native loot. It's just a matter of how to decide what sort of chests to add where.

It's impossible for me to generate my own chests using this unless forge has a hook i can use, and i'm able to add metadata that my mod recognizes. I'll check to see if such a hook exists, or is planned.

**Comment by Greymerk** [comment]
Another consideration to this point, by the way, is that my loot is not generated per chest in isolation. Every chest in the dungeon is generated, and then afterwards filled with precise measurements of specific loot. I can add exactly six diamonds to a level, spread out between all the chests if i want. The native minecraft loot system cannot do this.
