### ISSUE TITLE
Crash on generation in 1.10

### ISSUE THREAD

**Issue by ironphildo69** [Greymerk/minecraft-roguelike#59]
Hello, I have a issue with running Roguelike in 1.10. I thought this was a mod conflict but upon running it just on 1.10 with no mods I encountered the exact same error. I'v attached the error in the txt file for readability. If i'v missed something let me know, i dont often report bugs so i may have missed something. :)

[error_27062016_ironphildo.txt](https://github.com/Greymerk/minecraft-roguelike/files/334133/error_27062016_ironphildo.txt)

P.S thx for the awesome mod :)

**Comment by Greymerk** [comment]
I haven't released a 1.10 version yet.
