### ISSUE TITLE
Trap blocks become see-through while being mined

### ISSUE THREAD

**Issue by MidnightsFX** [Greymerk/minecraft-roguelike#62]
This technically applies to all of the blocks which assume the texture of their surroundings. But since the traps take more than a split second to mine, they can be used to provide visibility into the rest of the world if mined with a very weak pick or other tool.

![example](https://cloud.githubusercontent.com/assets/9042626/17422429/c7e85c90-5a66-11e6-8c2f-aecc029dc699.png)

Texture pack doesn't matter in this. As the block 'assumes' the blended texture of the block destroying sequence. Which is largely see through, thus providing vision past its self.

**Comment by Greymerk** [comment]
Whatever that block is, it's not related to this mod. If you're finding it in the dungeon that's probably because it's being placed there by another mod.

**Comment by MidnightsFX** [comment]
Thanks for correcting me there, sorry for reporting something not related to your mod.

Also thanks for making this mod, its awesome.
