### ISSUE TITLE
[1.10.2]dungeon generation will probably crash with newer forge versions above 2047

### ISSUE THREAD

**Issue by Tsukiumy** [Greymerk/minecraft-roguelike#63]
"Build 1.10.2-12.18.1.2047:
	LexManos: Make stair culling use actual state, and be more robust. Closes #3170"

crashlog
http://pastebin.com/6urfbi3G

when generating terrain got this crash 2 times, as i just updated forge, reverted back to 2046 and teleported to the problematic spot, probably every dungeon gen will crash the game whenever the people load the chunk with this placement.
dunno if its a forge side problem, will report there too just for the case

print of the affected block
http://imgur.com/a/G7nh1

**Comment by Tsukiumy** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/3174
just to be on safe side

**Comment by Tsukiumy** [comment]
firge side, fixed, sorry for te trouble.

**Comment by Greymerk** [comment]
Thanks for following up on this. Glad to see it was fixed.
