### ISSUE TITLE
[1.10.2] Error with Help Command 

### ISSUE THREAD

**Issue by YOYOK9** [Greymerk/minecraft-roguelike#67]
Not sure weather this is from your mod or sponge forge but figured i should bring it to your attention. I am using the latest version of roguelikedungeons and am getting this error when I do "/help" or "/?. 

http://pastebin.com/jdhvstxQ

Mc version: 1.10.2
Mod version: 1.10.2-1.5.4
Sponge version: 1.10.2-2073-5.0.0-BETA-1687

**Comment by ktole1999** [comment]
i get same thing and i am using sponge 2052. even using the helpfixer mod does not fix it.

**Comment by Greymerk** [comment]
Noone's added input on this, and I don't know anything about sponge personally, so going to close this.

It's not clear to me whether this is even connected to this mod just by looking at the crash log.
