### ISSUE TITLE
Custom dungion isnt spawning

### ISSUE THREAD

**Issue by mightydanp** [Greymerk/minecraft-roguelike#68]
http://pastebin.com/GDKt8iWe
http://pastebin.com/SY0tP9Kq
http://pastebin.com/iByUCkZb
http://pastebin.com/vQS7MYD3
http://pastebin.com/ktX4BkqV
http://pastebin.com/H7GzRBPk
http://pastebin.com/E0tDVgK5
http://pastebin.com/qVxqZN4P
http://pastebin.com/31jrEkWD
{
    "name" : "secrets",
    "levels" : {
        "0" : {
            "secrets" : [
                {"type": "SMITH", "num" : 2},
                {"type": "BEDROOM", "num" : 2}
            ]
        }  
    }
}
http://pastebin.com/d8H2jWK1

{
    "name" : "tower",
    "tower" : {
        "type" : "ENIKO",
        "theme" : {
            "base" : "TOWER",
            "primary" : {
                "walls" : {
                    "type" : "JUMBLE",
                    "data" : [
                        {"name" : "gregtech:gt.blockstones", "meta" : 9},
                        {"name" : "gregtech:gt.blockstones", "meta" : 11},
                        {"name" : "gregtech:gt.blockstones", "meta" : 12}
                    ]
                },
                "pillar" : {"name" : "gregtech:gt.blockgranites"},
                "stair" : {"name" : "minecraft:dark_oak_stairs"}
            },
            "secondary" : {
                "walls" : {"name" : "gregtech:gt.blockstones", "meta" : 11},
                "pillar" : {"name" : "gregtech:gt.blockgranites"},
                "stair" : {"name" : "minecraft:dark_oak_stairs"}
            }
        }
    }
}

---

{
    "name": "main",
    "inherit": [
        "loot_all",
        "loot0",
        "loot1",
        "loot2",
        "loot3",
        "loot4",
        "mobs",
        "themes",
        "generators",
        "tower",
        "rooms"
    ],
    "criteria": {
        "biomeTypes": [
            "PLAINS",
            "MEADOW",
            "SHRUBLAND",
            "COLD, CONIFEROUS, FOREST",
            "WET, SWAMP",
            "HOT, DENSE, WET, JUNGLE",
            "HOT, WET, JUNGLE, FOREST",
            "DENSE, SPOOKY, FOREST",
            "COLD, CONIFEROUS, FOREST, SNOWY",
            "COLD, CONIFEROUS, FOREST",
            "HOT, SPARSE, SAVANNA, PLAINS",
            "HOT, SPARSE, SAVANNA, PLAINS",
            "MESA, SANDY",
            "SPARSE, MESA, SANDY",
            "MESA, SANDY",
            "OCEAN, RIVER, SWAMP",
            "SNOWY, WASTELAND",
            "PLAINS, SANDY",
            "FOREST, SNOWY",
            "SANDY, SNOWY",
            "FOREST, BEACH",
            "HOT, DRY, PLAINS, SANDY",
            "WET, SWAMP",
            "DENSE, FOREST",
            "DENSE, FOREST",
            "HOT, DRY, PLAINS, SANDY",
            "HOT, DRY, FOREST, SANDY",
            "HOT, DRY, PLAINS, SANDY"
        ]
    },
    "overrides": [
        "LOOTRULES"
    ]
}

**Comment by mightydanp** [comment]
Added configs

**Comment by mightydanp** [comment]
20:17:05  [Info] [STDERR]: [greymerk.roguelike.dungeon.settings.SettingsResolver:<init>:79]: Error found in file _loot_all_levels.json
20:17:05  [Info] [STDERR]: [greymerk.roguelike.dungeon.settings.SettingsResolver:<init>:80]: null
20:17:05  [Info] [STDERR]: [greymerk.roguelike.dungeon.settings.SettingsResolver:<init>:79]: Error found in file main.json
20:17:05  [Info] [STDERR]: [greymerk.roguelike.dungeon.settings.SettingsResolver:<init>:80]: null

**Comment by Greymerk** [comment]
Sorry for the late reply on this issue. When "null" shows up like that it means there was uncaught exception somewhere. It's difficult to tell what went wrong in these cases.

On my end I need to go through these parts of the code and add exception handlers to report exactly what the cause of these failures are.
