### ISSUE TITLE
[1.10.2] WeaponCaseLoot Mod items are spawning in the custom dungeons, Please help me 

### ISSUE THREAD

**Issue by Budhvin** [Greymerk/minecraft-roguelike#69]
The weapon case loot mod provides items that spawn in weapons with a randomize chance, much like csgo. This mod should spawn in the items in dungeons and strongholds and other random structures, but outside a typical village, I haven't see it spawn in the dungeons. my friend said this could due to a conflict, but I am not good with coding so I am hoping you could help me. I am currently on the 1.10.2 patch

**Comment by Greymerk** [comment]
I'm not sure I understand the issue. Are you saying that these weapon cases aren't spawning in vanilla minecraft box dungeons?

I can tell you that my mod doesn't interfere with the forge loot system. My mod only reads from it to populate some of the chest loot in the dungeon. My mod also does not interfere with generation of any chests outside of the roguelike dungeons themselves.

**Comment by Sethervan** [comment]
I think he is trying to ask how to get a weapon case from the mod Weapon Case Loot to spawn in roguelike dungeons.  I've been plugging away at it for a while with no success.  There must be some special tag for the items.  The item name is "weaponcaseloot:weaponcase".  From what I can tell there appear to be 4 items with the same name.  I'm guessing a NBT tag or something would help but I haven't been able to figure out how to find that information.  Anyhow I just thought I'd help explain.  Hope that helps.

**Comment by Sethervan** [comment]
I finally figured it out in case anyone else was looking.  You must add the meta tag for the 4 different types of weapon cases.  Here's a sample line:
{"data" : {"name" : "weaponcaseloot:weaponcase", "meta" : 1}, "weight" : 4}

The meta information is as follows:
Sword First Edition - "meta" : 1
Sword Second Edition - "meta" : 2
Bow - "meta" : 3
Ring - "meta" : 4

Hope that helps.  Happy modding!

**Comment by Budhvin** [comment]
wait, where do i add the meta tags?

**Comment by Greymerk** [comment]
if you mean nbt data, you can add it with the "nbt" tag
"meta" is what's also known as "item damage" such as the durability of a pickaxe, or the color of a piece of dye.
