### ISSUE TITLE
[1.10.2] Cannot get custom dungeon inheritance to work

### ISSUE THREAD

**Issue by belathus** [Greymerk/minecraft-roguelike#70]
Here are the two dungeon json files I'm trying to get working:
http://pastebin.com/gCCQibu3
http://pastebin.com/mDN5Ku4B

If I copy the "loot_rules" setting into the first file, it works fine, but if I leave them as separate files, the dungeons spawn with no loot at all. The file name of the second file, the inherited file, is "_loot0.json" while the first file is "botania.json."

I've tried a lot of different inherits for different things than just loot, but I haven't had any success with it at all.

**Comment by EnderStar** [comment]
Hi, try to change the _ for a number or an a, if it depends on the OS it may be the problem as some OS ignore the _ to order alphabetically

**Comment by Greymerk** [comment]
This was likely also fixed by the pre-release build here:
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.5.5.2

It looks to be the same exact issue.
