### ISSUE TITLE
[1.10.2] Skeleton spawners only spawn melee skeletons

### ISSUE THREAD

**Issue by Robijnvogel** [Greymerk/minecraft-roguelike#71]
I have pre-generated a world using MDE-Core and after loading the world on a strictly Vanilla (Realms) server, I found that all skeleton spawners inside the Roguelike dungeons only spawn Skeletons that aren't wielding bows. This does make the dungeons a little harder, but I'm not quite convinced that this behaviour is intentional.

Also, this may be an other issue entirely, but, while pre-generating a world the following line was written in the console output several times:
`[11:13:26] [Server thread/INFO] [STDOUT/]: [greymerk.roguelike.worldgen.spawners.Spawnable:generate:66]: Not a mob spawner.`

**Comment by Greymerk** [comment]
If you plan to pregenerate a world for vanilla then go into the config and change rogueSpawners to false. This will use vanilla spawners without metadata. The reason why this is necessary is rather arcane, so i won't go into it. But that's the workaround for now.

**Comment by Robijnvogel** [comment]
Clear enough,

The quoted console output happens on the modded pre-gen server though.

**Comment by Greymerk** [comment]
The message just means that a spawner failed to generate for some reason. just ignore it. That message shouldn't even be there tbh. it's not really a problem.

**Comment by Robijnvogel** [comment]
You're not even interested why it's there although it shouldn't? :P

**Comment by Greymerk** [comment]
What i mean is that I should remove that message from the codebase. If a spawner fails to generate then there's probably a good reason and it's not really an issue that this happens sometimes.

Also I should get rid of all debugging information that's going to standard output, it should be sent to the forge log instead. That's what i meant. But it's not really an actionable warning, so I'll just remove the message.

**Comment by Greymerk** [comment]
FYI: As of the latest release for 1.11 you no longer need to set configurations to fix this. mobs will spawn with random equipment in vanilla, or without the mod installed. So you can ignore what i said above.
