### ISSUE TITLE
[1.10.2]Statistic by Greymark has a stacksize of 0

### ISSUE THREAD

**Issue by The-Fireplace** [Greymerk/minecraft-roguelike#74]
As the title says, that book has a stacksize of 0 when it shows up in the chests. Tested in the Brick house dungeon.

**Comment by Greymerk** [comment]
I've checked this with both the latest version of forge and roguelike dungeons. Not seeing any evidence of this being the case.

**Comment by The-Fireplace** [comment]
Just looked at a different house, and the book doesn't have stacksize 0. Perhaps it was a one-time error.
