### ISSUE TITLE
Trouble with dungeon commands

### ISSUE THREAD

**Issue by SpikesterMeister** [Greymerk/minecraft-roguelike#76]
Maybe I'm doing something wrong or something I'm not understanding?

Running MC 1.7.10 FTB Infinity Evolved

I've been messing around in a creative world and I wanted to see all the different types of towers. So I tried to run the command /roguelike dungeon here [setting]. I replace [setting] with the names of the towers you have already in the mod. However every time I run the command, example: /roguelike dungeon here EthoTower, it always says it cannot find the file.

What am I doing wrong?

**Comment by Greymerk** [comment]
You want to create a directory called "settings" here: minecraft/config/roguelike_dungeon/settings

Then inside settings place this file: [tower.txt](https://github.com/Greymerk/minecraft-roguelike/files/676656/tower.txt).

You'll notice that in that file is a field called "name" and name (tower in this case) is what you put in your command. in this case it'd be "roguelike dungeon here tower"

All of your customization goes inside the tower.json

By the way, I put an easteregg in the mod called citadel which you can spawn like roguelike citadel X Z which spawns a bunch of random towers with random themes. You might find it interesting.

**Comment by SpikesterMeister** [comment]
Thank you very much!!! Now I understand how it works. I tried the citadel, it is pretty cool. :+1:  The random themes are awesome!
