### ISSUE TITLE
Unparsable JSON Error

### ISSUE THREAD

**Issue by sigurdtheone** [Greymerk/minecraft-roguelike#77]
Error:
[21:06:45] [Server thread/ERROR] [FML]: The mcmod.info file in RoguelikeDungeons-1.11.2-1.6.2.jar cannot be parsed as valid JSON. It will be ignored

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 10 column 3

Forge Version:
1.11.2-13.20.0.2201

MC version: 
1.11.2

OS version:
Ubuntu Server 16.04 LTS

Java Version:
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

**Comment by sigurdtheone** [comment]
Fixed by removing the trailing comma after "authorList"

**Comment by Greymerk** [comment]
Thanks. i removed a few lines in the file and forgot to remove the trailing comma. oops.
