### ISSUE TITLE
random crashed in 1.10.2

### ISSUE THREAD

**Issue by Atwise** [Greymerk/minecraft-roguelike#79]
I keep getting random server/game crashes in the newest 1.10.2 jar 1.5.5 file. This was the crash log file.

[crash-2017-01-13_21.31.55-server.txt](https://github.com/Greymerk/minecraft-roguelike/files/705756/crash-2017-01-13_21.31.55-server.txt)

**Comment by Greymerk** [comment]
This was a problem in forge 1.11 and I suppose has been included recently in 1.10.2. Will have to backport the change for this. Thanks for letting me know.

**Comment by Greymerk** [comment]
Actually, i'm going to assume for now it's related to this issue. Other mods are suffering from this issue as well, related to TerrainControl.

https://github.com/MCTCP/TerrainControl/issues/500

I don't think this is something I can fix on my side.
