### ISSUE TITLE
add loot cyclic

### ISSUE THREAD

**Issue by arma258** [Greymerk/minecraft-roguelike#80]
I would add cyclic loot but do not know how to do it you could help me?

**Comment by AutisticMC** [comment]
I would add a loot spawning system based on the biome structure spawns in.

**Comment by Greymerk** [comment]
Kind of a broad question actually. but here's a very basic example of how it's done:

[cyclic.txt](https://github.com/Greymerk/minecraft-roguelike/files/715037/cyclic.txt)

This setting just adds a few items to the first level of the dungeon. I added weighting to the air charm just to show that you can do that if you want to. Note that the charms are missing a chest type, this means they're added to any chest on the level regardless of type.

Note that in this case i'm not overriding the loot system, i'm just adding in a few items. You can totally override the loot system and redo it from nothing if you want. But that's a lot more work.

If you're going to do something more complicated than adding a few items, i would suggest splitting your loot settings into multiple files, testing them separately, and then combining them using inheritance.
