### ISSUE TITLE
Getting Double the Amount of Loot Specified

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#83]
Sometimes, I would get double the number of loot. For example, if I specify 8 in the quantity property in the loot files, I would get 16 items per chest. I don't know what's causing it but minor changes often causes the loot to go back to normal.
Loot JSON for that Floor: http://pastebin.com/a7jfbEAB
Old Image of Abnormal Loot
![2016-12-30_23 52 11](https://cloud.githubusercontent.com/assets/11682762/22172000/59c52d0e-df6a-11e6-97e6-88ee847bbd4d.png)

**Comment by EnderStar** [comment]
Can you provide a screenshot of the loot with the correspondic config file that causes it?
Thanks!

**Comment by Alan19** [comment]
![2017-01-22_15 55 31](https://cloud.githubusercontent.com/assets/11682762/22185977/e1a59cec-e0bc-11e6-82a8-2a19db7dda9f.png)
The json for that chest is in the first post. I fixed the link.

**Comment by Greymerk** [comment]
Your file looks okay to me. Can't spot any issues. Are you inheriting in another file? could be somehow the rule is being added twice. Just a guess.

**Comment by Alan19** [comment]
Here's all the configs I'm using. I'll double check if any of the files are inheiting twice.
https://github.com/belathus/Wanderlust-Renewed/tree/master/config/roguelike_dungeons/settings

**Comment by Alan19** [comment]
Do other dungeons inheriting the same loot files cause problems?

**Comment by EnderStar** [comment]
How to fix it: Learn java and download eclipse so you can code a fix or even hardcode your loot, it may take months.
Easy fix: Divide itemcount by 2 XD

**Comment by Greymerk** [comment]
Oooh.... You know what it probably is. You are using biome as your criteria for the loot and in some cases perhaps both dungeons are eligible to spawn in the same place (eg: SPOOKY FOREST). So maybe it's actually combining the loot rules from both biome dungeons by adding them twice.

Will have to try that out and see if that's a thing that happens.

**Comment by Alan19** [comment]
But won't that mess up the levels? Nothing else is wrong except for the loot.

**Comment by Alan19** [comment]
After spawning a dungeon in a biome that doesn't overlap with any other files, I'm still getting double loot. Maybe it has something to do with the secret room that I added to abyssalcraft.json

**Comment by Greymerk** [comment]
You put this inside a theme by the way, it shouldn't do anything.

https://github.com/belathus/Wanderlust-Renewed/blob/master/config/roguelike_dungeons/settings/abyssalcraft.json#L329

**Comment by Alan19** [comment]
Thanks. I removed it and also tried removing the other loot files. I'm still getting double loot.
![2017-01-22_22 42 10](https://cloud.githubusercontent.com/assets/11682762/22191034/72acf6d0-e0f5-11e6-8e55-b4e3fe3e7ca5.png)

**Comment by Alan19** [comment]
I'm going to try removing each file until I find which file is causing it.

**Comment by Greymerk** [comment]
What mod/minecraft version is this for anyway?

**Comment by Alan19** [comment]
1.10.2

**Comment by Greymerk** [comment]
I managed to reproduce this bug in 1.10.2 and 1.11.2

will take a look at it in the debugger, hopefully give me a better idea as to what's going on.

**Comment by Greymerk** [comment]
I think I managed to fix it. Will need to do more testing, then I'll put up a build and you can try it out.

**Comment by Greymerk** [comment]
Try this build and see if it works.
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.5.5.1

**Comment by Greymerk** [comment]
Never mind.. New bug caused by the fix. working it out now.

**Comment by Greymerk** [comment]
This one fixes bug.. which was that multiple inheritances in a file would conflict and override eachother
https://github.com/Greymerk/minecraft-roguelike/releases/tag/v1.5.5.2

**Comment by Alan19** [comment]
Trying it now

**Comment by Alan19** [comment]
It's working :)
Before: ![2017-01-22_15 55 31](https://cloud.githubusercontent.com/assets/11682762/22233782/d7c5f15e-e1c0-11e6-88b9-6d3ef99f0c77.png)
After: 
![2017-01-23_22 57 22](https://cloud.githubusercontent.com/assets/11682762/22233788/ecd15d22-e1c0-11e6-8cdc-604df3cb40cf.png)

**Comment by Greymerk** [comment]
Great. Looks good.

**Comment by Alan19** [comment]
I'm getting double loot again. The latest configs are still on the GitHub page.
