### ISSUE TITLE
Specifying Rooms Causes Halls to Become 3x3 Corridor with Nothing in It

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#84]
![2017-01-20_23 31 01](https://cloud.githubusercontent.com/assets/11682762/22171990/085dfe0a-df6a-11e6-9096-e28da95f9398.png)

Link to JSON: http://pastebin.com/ek6C697x

**Comment by EnderStar** [comment]
Have you fixed the problem?

**Comment by EnderStar** [comment]
I think that there are too many rooms for that small range so they dont fit and this happens. try increasing the range to 100 to test and decrease it until this starts to happen to get the minimum range

**Comment by Alan19** [comment]
I decreased the number of rooms to 10 and increased the range to 100 and it's still happening
![2017-01-22_15 58 54](https://cloud.githubusercontent.com/assets/11682762/22185930/25aaaf00-e0bc-11e6-98f3-92fa8d68f81d.png)

Here is the json I'm using:http://pastebin.com/tWmHCusA
The part with the rooms is at the bottom
"4":{
            "numRooms":15,
            "range":100,
            "rooms":[
                {
                    "mode":"SINGLE",
                    "type":"LAB"
                },
                {
                    "mode":"RANDOM",
                    "type":"STORAGE",
                    "weight":5
                }
            ],

**Comment by Greymerk** [comment]
Ok, I'll admit this is kinda my fault. "single" "random" apparently is case sensitive and needs to be lower case.

It really shouldn't be case sensitive, I know.

Doesn't explain why the hallways are blank though. I wasn't able to reproduce that issue.

**Comment by Alan19** [comment]
Maybe it's because I'm using Foamfix anarchy edition

**Comment by Alan19** [comment]
I'm going to test it right now

**Comment by Greymerk** [comment]
Your screenshot kinda looks like the result of a crash part way through the dungeon generation. It actually looks rather like the generator finished creating the hallways and then stopped before creating the rooms and hallway decorations.

**Comment by Alan19** [comment]
I got it to work after adding the changing single and random to lowercase. The only thing I changed from the first time was increasing the range and decreasing the number of rooms in the level settings.

**Comment by Alan19** [comment]
It seems that adding room replaces the rooms that would spawn normally completely without overriding. Is this intended?

**Comment by EnderStar** [comment]
@Greymerk Is possible to add nbt data to the spawners or the mobs that spawn? Could you tell me how?
I tryed this:
```
{
	"name" : "spawners",
	"criteria" : {},
	"levels" : {
		"all" : {
			"spawners" : {
"CREEPER" : [
{
                                       "name" : "Blaze",
					"meta" : {
						"Attributes" : [
							{
							"Name" : "generic.maxHealth",
							"Base" : "100.0"
							}
						]
						}
}
]
}}}}
```
But adding that meta disables the config.
Thanks!

**Comment by Greymerk** [comment]
It's a behavior I never got around to implementing. Currently if you specify a list of rooms it just overrides all the rooms for that level.

**Comment by Alan19** [comment]
By the way, you didn't list the reward room on the wiki and do you know which rooms contain items from the block list @Greymerk ?

**Comment by Alan19** [comment]
I'm also getting this in B2 even though I increased the floor size

**Comment by Greymerk** [comment]
I used to put "Block" chests more commonly in the dungeon. Now they're only in the storage room as i recall.

**Comment by Greymerk** [comment]
Regarding this bug, I think what I'll try to do is make the system throw a warning if an invalid name is given.

**Comment by Alan19** [comment]
I got an error log when this happened on B2

**Comment by Alan19** [comment]
Trying to find it right now

**Comment by Greymerk** [comment]
probably just says "null"

**Comment by Greymerk** [comment]
I've implemented this enhancement in the latest build to provide meaningful warnings if an incorrect name is given.
