### ISSUE TITLE
Trouble with configs

### ISSUE THREAD

**Issue by EnderStar** [Greymerk/minecraft-roguelike#85]
Hi, with looting:0 mobs drop loot (normal and armor/weapons) and how can i remove some mobspawners from all the dungeons, i added _mobs.json to the settings folder with the names of the mobs that i want to be spawned but that isnt affecting the dungeons, other mobs still spawn, do i have to add other files? Is possible to do what i want to do without changing any other feature of the mod?
Also i tryed to add nbt data to the mobs, this is how i did it:
```
{
	"name" : "mobs",
	"levels" : {
		"all" : {
			"spawners" : {
				"SILVERFISH" : [
					{"name" : "Silverfish"}
				],
				"CAVESPIDER" : [
					{"name" : "CaveSpider"}
				],
				"SPIDER" : [
					{"name" : "Spider"}
                                        {"meta" : "{Attributes:[{Name:"generic.maxHealth",Base:100.0}]}"}
				]
			}
		}
	}
}
```
Is everything right there? 
Thanks!

**Comment by Alan19** [comment]
Have you tried overriding?

**Comment by EnderStar** [comment]
Now i added the main.json file with override, here it is:
```
{
	"name" : "main",
	"inherit" : [
		"mobs"
	],
	"overrides" : [
		"SPAWNERS"
	]
}
```
I only have this file and _mobs.json, i dont know if  "SPAWNERS"  is the right name

**Comment by Alan19** [comment]
I think inherit might be broken when spawning specific dungeons so any dungeon spawned without the name should have it.

**Comment by EnderStar** [comment]
Im realy confused about how the settings work so possibly i did osmething wrong, can you tell me what i have to do to only disable some mobspawners and add nbt data to the mobs (i know how to add nbt data with command blocks but i dont know where where i have to add it with this mod)?
Thanks!

**Comment by Alan19** [comment]
I think you can only disable all of the mob spawners or add them.

**Comment by EnderStar** [comment]
Thanks for your answer, i just found a one hour tutorial video that explains a lot , now i know how to disable some mobs, but the nbt part is a mistery XD, i tryed this to add atributes to the mobs:
```
{
	"name" : "spawners",
	"criteria" : {},
	"levels" : {
		"all" : {
			"spawners" : {
"CREEPER" : [
{
                                       "name" : "Blaze",
					"meta" : {
						"Attributes" : [
							{
							"Name" : "generic.maxHealth",
							"Base" : "100.0"
							}
						]
						}
}
]
}}}}
```
thisdoesnt work but if i remove the meta it works and replaces the creeper spawners with blaze spawners :D Do you know how is the format to add nbt data?
Thanks!
