### ISSUE TITLE
nbt data to spawners

### ISSUE THREAD

**Issue by EnderStar** [Greymerk/minecraft-roguelike#86]
Hi, im trying to add nbt data to the spawners, reading the wiki seems to be possible using the "meta" option but i wasnt able to do it, here is my config (it doesnt work):

```
{
	"name" : "spawners",
	"criteria" : {},
	"levels" : {
		"all" : {
			"spawners" : {
"CREEPER" : [
{
                                       "name" : "Blaze",
					"meta" : {
						"Attributes" : [
							{
							"Name" : "generic.maxHealth",
							"Base" : "100.0"
							}
						]
						}
}
]
}}}}
```
If i remove the meta it works and replaces the creeper spawners with blaze spawners :D 
there im adding nbt directly to mobs, i  tryed to use SpawnData i case that this modifyes the mobspawnners directly but it didnt work.
Thanks!

**Comment by Greymerk** [comment]
I think maybe this feature broke with some minecraft update. Will have to get back to you on this.

**Comment by Greymerk** [comment]
I did some work on this and I seem to have made some headway. This feature was just not working at all due to some changes that happened a while back.

![2017-01-26_14 52 03](https://cloud.githubusercontent.com/assets/4789166/22353863/65cd80f8-e3d7-11e6-8a84-3511b104f02d.png)

**Comment by EnderStar** [comment]
Thanks for testing it!

**Comment by Greymerk** [comment]
it should look like this:

```
{
	"name" : "foo",
	"levels" : {
		"all" : {
			"spawners" : {
				"ZOMBIE" : [
					{
						"name" : "Blaze",
						"equip" : false
					}
				]
			}
		}
	}
}
```

but this may not work until the fixes are published. The build is in a messy state since i've been revising and testing the settings for the past while.

**Comment by Greymerk** [comment]
This is what the jeb sheep setting was:
```
{
	"name" : "spawner",
	"levels" : {
		"all" : {
			"spawners" : {
				"ZOMBIE" : [
					{
						"name" : "Sheep",
						"equip" : false,
						"meta" : {
							"id" : {"type" : "STRING", value : "Sheep"},
							"CustomName" : {"type" : "STRING", "value" : "jeb_"}
						}
					}
				]
			},
			"theme" : {
				"primary" : {
					"floor" : {
						"name" : "minecraft:grass"
					}
				},
				"secondary" : {
					"pillar" : {
						"name" : "minecraft:glowstone"
					}
				}
			},
			"segments" : {
				"segments" : [
					{"type" : "SPAWNER", "weight" : 1},
					{"type" : "WHEAT", "weight" : 1},
					{"type" : "FLOWERS", "weight" : 1}
				],
				"arch" : "ARCH"
			}
		}
	}
}
```

I added glowstone pillars and grass floors to satisfy the sheep spawning conditions.

**Comment by Greymerk** [comment]
I've posted the jars for 1.11.2 and 1.10.2 that include the fix for this. Try it out.

**Comment by resinate** [comment]
whats the one to change skeletons to wither skeletons?
