### ISSUE TITLE
Secondary Floor is Never Used

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#87]
There are a lot of places where the blocks used for the wall is used for the floor when they could have used the secondary floor blocks instead.
The floor is made using blood bricks from railcraft, the material being used as the primary walls but it might be a better idea to use what is in the secondary or primary floor blocks that are specified in the theme.
![2017-01-22_19 15 07](https://cloud.githubusercontent.com/assets/11682762/22233809/1aa9e7b4-e1c1-11e6-801e-7d53105f2833.png)
![2017-01-22_19 07 42](https://cloud.githubusercontent.com/assets/11682762/22233812/1fc8ceae-e1c1-11e6-82b0-9b5dbc4245b8.png)

**Comment by Greymerk** [comment]
I added floors as a theme feature after creating a lot of the rooms. I just haven't yet gone back to update some of the rooms to actually use floors instead of wall blocks.
