### ISSUE TITLE
Certain Rooms Ignore Theme

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#88]
Rooms like CAKE and AVIDYA ignore the theme. It makes the room feel very out of place.
![2017-01-23_23 00 17](https://cloud.githubusercontent.com/assets/11682762/22233904/fb4df292-e1c1-11e6-867d-8bc1314b9da9.png)

**Comment by Greymerk** [comment]
That's intended. There's a variety of rooms with statically assigned blocks for one reason or another.

The Avidya room is a mindcrack reference. Similar to the BTeam secret room, it has its own very specific design.

The cake room is kind of meant as a joke. It's supposed to look out of place.
