### ISSUE TITLE
New Redstone Structures

### ISSUE THREAD

**Issue by AutisticMC** [Greymerk/minecraft-roguelike#90]
[Tutorial+Bunker.zip](https://github.com/Greymerk/minecraft-roguelike/files/730400/Tutorial.Bunker.zip)
[PVP+Fight+Arena+TUT.zip](https://github.com/Greymerk/minecraft-roguelike/files/730402/PVP.Fight.Arena.TUT.zip)

**Comment by Greymerk** [comment]
What is this?
