### ISSUE TITLE
Controlling built-in dungeon spawns

### ISSUE THREAD

**Issue by RiverC** [Greymerk/minecraft-roguelike#91]
I need to control where the built-in dungeons spawn. How do you do this? I do not see any clear instructions even for a more advanced user - so let me give an example of what I've been doing.

- I looked in the source, found settings / builtin
- I could not find the "name" each of these settings has. 
- I guessed but it did not resolve. For example, builtin settings "ice" theme does not seem to be overridden by a settings file with `"name" : "ice"`

`/config/roguelike_dungeons/settings/ice.json
`
```
{
    "name" : "ice",
    "criteria" : {
        "biomes" : [
            		
            ],
		"biomeTypes" : [
			"IGNORE"
            ]
	 }
    }
}
```

This is an attempt to prevent the ice theme dungeon from spawning. (There are presently no biomes in a world which have a biome dictionary entry "ignore".)

When I try `"/roguelike dungeon here ice"` it tells me that ice is not found.

[edit: turns out, I'm not sure how that was working, I can't reproduce the problem of "tower" working when there is no setting named for it.]

Clearly I am misunderstanding what any of these things mean, but I'm not sure in what way.

It looks like RLD picks a spot for a dungeon and then determines the theme it will use based on the themes available, including custom settings, and if it finds no builtin setting it spawns a default themed dungeon. 

If so, this is a problem, as it prevents me from controlling where dungeons can spawn; it only seems to allow me to change the theme of the dungeon that will show up. 

Here is my request:

1. Some documentation on the built-in theme/dungeon settings, a list of their actual names so you can test-spawn them by command in the world, and what an example file would look like to override whatever properties they have which can be overridden, including an explanation of how spawning works (as of right now, it's unclear to me if my explanation above is correct.) 

2. A way to prevent dungeons from spawning in certain places; however you implement this is up to you, I don't really understand the structure and algorithm just from my cursory glance, so I can't say. Further, some kind of documentation on this. For example, "If you want to prevent forest theme dungeons from showing up, create this file with this name and "name" attribute (If it matters) and put this line in. If you want to prevent all built-in dungeons from spawning do this, if you wish to prevent any dungeons from showing up in certain biomes, do this, etc." 

The problem I'm trying to tackle is to ensure certain sets of biomes in my world have particular types of structures in them, and I really really really want to include Roguelike dungeons in some areas, but not in others. I have control over the biomedictionary entries as well as the list of biomes and where they can spawn north and south of the player's spawn; but what I don't yet have a grasp of is what settings files I need to create to either

1. Ensure that in a certain group of biomes, ONLY x type of dungeon spawns which has particular items and loot ONLY.

2. Or, barring spending the time of perfecting those dungeons, for now forbidding ANY dungeons spawn in those areas.

**Comment by Greymerk** [comment]
First of all, build-in settings simply don't have names at all, and cannot be called by name.

I think for number 1 the answer is to include complete settings. including tower, all levels, all loot, everything. Custom settings will take precidence over build-in settings.

for number 2, yeah, there's no way to blacklist spawning in a given biome, or biome type, to automatically block everything but a given biome. Will look into some sort of option.

**Comment by RiverC** [comment]
Thanks for the quick response, and having fooled around a bit more, I see how that works. In the end I may have to nerf all of the built-ins and make a few custom dungeons that re-implement them in my desired biomes. However, the whole modpack might end up getting axed due to HarvestTweaks not working correctly.

**Comment by Greymerk** [comment]
You make a good point. It may be suffient to add a configuration to disable built-in themes, so that only those you add will spawn.

**Comment by RiverC** [comment]
As a coder, I'm all for the most elegant and non-intrusive solution to the problem, even if it isn't quite what the client "expects" ! When I started developing a modpack, I discovered to my dismay that a lot of mods make assumptions about what other things will be present (or not--) and this informs how they balance their mod, many times making things far too easy or far too hard - but then I discovered that if you just switched off some features (or prevented them from showing up using biomedictionary entries, tweaking their recipes, making them quest rewards only, etc) it helped balance things. But then I discovered to my further dismay that many modders wouldn't let you disable certain features at all, I suppose assuming players who wanted to disable them were wimps... and so on, ad infinitum. It's alternating turtles all the way down!

In the meantime I might just fork HarvestTweaks and fix it myself.

**Comment by Greymerk** [comment]
I'm sure many mod-makers are like me in that they started working on their mods for their own amusement. It was meant to be something to play with my friends and I just crafted an experience that was suitable to me. Creating a way for other people to re-purpose the mod for their own ends has always been secondary. It's an ongoing evolution that involves much backtracking in order to even develop the tech that makes hot-swapping features possible.

I don't personally object to any sort of adaptation, however I always feel as if i'm walking a tight-rope between my own vision and the requests of other people. My challenge has always been to enable both to co-exist.

**Comment by Greymerk** [comment]
I'm thinking to provide some sort of global option to disable built-in spawns, but then also introduce namespaces to settings. This would allow you to reference built-in settings by namespace like maybe "inherit" : ["roguelike:ice"] or something to that effect. so you could have your own setting named ice and it wouldn't collide with the builtin namespace. Then you could apply your own criteria to the spawning.

```
{
	"name" : "test",
	"inherit" : [
		"roguelike:jungle"
	]
	"criteria" : {
		"biome" : "Savanna"
	}
}
```

if you disabled built-in spawns this would result in the jungle theme spawning in the savanna but nothing else anywhere would.

**Comment by RiverC** [comment]
so the criteria could be any criteria (which includes biomeType)

I think that's a light-weight way to deal with it. My modpack controls what biomes appear where, and along with other things puts certain biomes always far from the player. I had wanted to make more, and more challenging features appear as the player travelled further, and wanted to disable the dungeons from spawning in the vicinity of the spawn area. With RecurrentComplex I was able to identify and override the settings for all of the built-in objects so that structures where you could get, say, tons of wheat or something of that sort, which might make sense in other play-conditions, would no longer appear in those zones. 

I'm endeavoring to not write my own "tweaks" mod on account of not wanting to deal with writing Java again - and also as a showcase of what can be done by combining the right mods and changing their settings for effect.

In the end, it does look like I will need to create my own mod just to supply the "dungeon brick" elements for particular puzzles. They are bricks with certain blast resistances and harvest levels that limit where you can get, when. The downside is that each dungeon, even randomly generated, has to be playtested rather extensively to ensure they're not made impossible by the fact that this or that section of wall is presently or generally un-mineable.

In the end, I might provide it as a general mod (though I'm loath to do so, because I don't want to have to support it outside of my modpack) which gives you configurable "challenge" blocks that can be given whatever texture and mining level you want, according to configs. 

Meanwhile, my dungeon ideas remain rather lame if you can just cut through whatever walls you want with whatever tools you want. C'est la vie!

**Comment by Greymerk** [comment]
Could add a criteria which is distance from world spawn.

**Comment by Greymerk** [comment]
It's been very challenging grappling with this problem, but one thing I've decided is that the way that settings are applied did need some revision. This mod originally didn't have any notion of themes or settings, all of that was hard coded. That hard coding informed certain design decisions which I can now get rid of and do better.

The problem I'm having is how to create a system that allows top to bottom changes to specific types of dungeons as well as cross cutting feature changes, like changing the loot in all dungeons to add one item. It's surprisingly difficult to juggle those two needs.

**Comment by Greymerk** [comment]
I've added a new boolean tag on settings called "exclusive" if it's missing then it's assumed false. Any non-exclusive settings are applied on top of any other settings if otherwise valid. Two exclusive settings must be chosen through a random dice roll.

This exclusive tag will allow you to do things like change loot, or make minor changes to all dungeons given a criteria, without having to explicitly change them.

Thankfully this approach doesn't change how anything worked before, it just adds a new way to define different dungeons individually, while still being able to make small universal tweaks at the same time.

**Comment by RiverC** [comment]
By the way, I've gotten back around to trying to reimplement this. If, for example, I wanted to prevent dungeons from spawning at all in the Ice Plains, is that yet possible? If so, what would I name the settings file and what tags would be required, i.e.

file named `settings/default.json`

```
{   
     "name":"default",
     "exclusive":true,
     "criteria" : {
              "biometypes" " [ 
                    "DESERT", "HOT", "TEMPERATE", "SWAMP"
               ]
     }
}
```
