### ISSUE TITLE
Specify door types in themes

### ISSUE THREAD

**Issue by Syndaryl** [Greymerk/minecraft-roguelike#92]
At the moment, doors are hard-coded to be Oak. There are other doors in the later versions of Minecraft vanilla, and of course many mods add doors to go with their wood types. It would be nice to be able to specify what to use for the door in the Theme, as Oak doesn't really go with all wood types.

**Comment by Greymerk** [comment]
Thanks for bringing this up, I had noticed it myself at one point but kinda forgot about it.

Good idea to add it into the theme.

**Comment by Syndaryl** [comment]
Make sure to have different settings for the Wood (e.g. easily opened doors) and Iron (for the zombie spawner trap rooms). Mods add doors of both types (BaseMetals/ModernMetals in particular adds a gazillion "Iron" type doors in lots of colours, making it easy to colour co-ordinate.

**Comment by Greymerk** [comment]
What i'll probably do is just add doors to the block sets, so you can have two different door types per level theme.

As for the coloured doors, i get a bit suspicious when i hear about stuff like that, often those are implemented as tile-entity blocks, which are very difficult to produce settings for.

**Comment by Greymerk** [comment]
Speaking of which, I've also been meaning to add "lightblock" in there as well so glowstone can be changed out for something else.

**Comment by Syndaryl** [comment]
The ones from BaseMetals/Modern Metals just extend from net.minecraft.block.BlockDoor (and net.minecraft.block.BlockTrapDoor). They're not "in game dyable/colourable doors" or doors that get "decorated" with other blocks or something, they're "one door object for each metal, thereby giving each a unique texture". Just like wood doors.

**Comment by Greymerk** [comment]
It sounds like it should be fine then.

**Comment by Greymerk** [comment]
I've made it work like this. It's unfortunate that that metals mod isn't at 1.11.2 since that's the version i do dev work in. Will have to back port all this to 1.10.2 eventually.

```
{
	"name" : "doors",
	"levels" : {
		"0" : {
			"theme" : {
				"base" : "OAK",
				"secondary" : {
					"door" : {
						"name" : "minecraft:dark_oak_door"
					}
				}
			}
		}
	}
}
```

**Comment by Greymerk** [comment]
This change is included in the jars I posted tonight.
