### ISSUE TITLE
Server console- NPE DungeonBTeam.generate

### ISSUE THREAD

**Issue by ProsperCraft** [Greymerk/minecraft-roguelike#93]
https://gist.github.com/ProsperCraft/d40b26e4e4dea8abd64c20b7f78c32c3

Modpack- Elf Squared 3.8.0E  for 1.11.2

This stacktrace showed up in console when doing a large 10k by 10k worldgen.

RoguelikeDungeons-1.11.2-1.6.3

**Comment by Greymerk** [comment]
It looks like one of the chests failed to generate and that line of code attempts to access a null chest reference. what seed did you use anyway? Kinda wish I could replicate this issue, but I gather you don't know where exactly this happened.

**Comment by ProsperCraft** [comment]
Sorry no, it was on a new server with 12 people running in different directions.

**Comment by Greymerk** [comment]
I've tried to address this issue by making the Treasure system properly handle cases where chests cannot be placed in the world for some reason. This should prevent this NPE from ever happening.

Will be included in the next update.
