### ISSUE TITLE
MST generator not working

### ISSUE THREAD

**Issue by Alan19** [Greymerk/minecraft-roguelike#94]
When I use the MST generator for a dungeon, nothing seems to be different. Is the MST generator supposed to randomize the base for the floor theme or does it do something else?

**Comment by Greymerk** [comment]
The MST generator looks more like a square maze. by default you'll see it on the third level of the dungeon, aka "crypt" level.

I'll make sure to look into whether it's parsing properly.

By the way, it's yet another enhancement pending to add more options to the generators... and eventually to add more generators. They're meant to be the algorithm by which levels take shape.

**Comment by Alan19** [comment]
Is it possible to randomize the theme of each floor or the tower?

**Comment by Greymerk** [comment]
I've thought about that. would be a fun feature. Right now, no.
