### ISSUE TITLE
question: adding ender io

### ISSUE THREAD

**Issue by forestasog** [Greymerk/minecraft-roguelike#96]
whenever i add ender io items it totally removes the loot table, like i put it in "level 1" and all of the chests in level 1 are empty.
i tried {"name" : "enderio:darkSteel_sword"} and {"name" : "darkSteel_sword"} with and without enchantments.
also i tried the same thing with various other dark steel loots.  i can get other mods to work with the loot tables.

this is in 1.10.2 with roguelikedungeons-1.10.2-1.5.6

also as a side note, i was wondering if "weight" could be in decimals, like .1

**Comment by Greymerk** [comment]
Can you actually post your setting so i can look at it? Or at least a simple example which causes the issue.

as for weight, no, it's stored as an integer. If you want one item to be 0.1 of another. just make the first item 1 and the other 10. There's no particular advantage to using fractional numbers.

**Comment by forestasog** [comment]
http://pastebin.com/NpLFiUct
http://pastebin.com/b2FYwSG3

**Comment by forestasog** [comment]
http://pastebin.com/nwQsNC3C - loot
http://pastebin.com/unSHDcic - loot all
http://pastebin.com/XMMm8uHb - loot 0
http://pastebin.com/DMQm1tUJ - loot 1
http://pastebin.com/LN1utmDP - loot 2
http://pastebin.com/0660v9ii - loot 3
http://pastebin.com/mvDaNQiv - loot 4

ok so apparently it's not ender io cause i just finished level 3 and 4 and they work with ender io,  idk i'll try to scour it to see what i did wrong >.<

**Comment by Greymerk** [comment]
try removing:

```
    "overrides" : [
        "LOOTRULES"
    ],
```
from your "loot all" file.

What that does is reset all previously defined loot rules. You want to use this only if your intention is to empty all the chests and define your own loot.

**Comment by forestasog** [comment]
ok i tried removing it...i actually did want that on.
the result of removing it was that my custom loot files now add nothing, but the default loot does appear in all 5 levels of the dungeon.

**Comment by Greymerk** [comment]
Oh ok. well you should start by validating your JSON.
I found at least one mistake in your syntax which would cause it to fail.

One of the things I'm currently working on is making in-game error reporting a little better so it's easier to know what's gone wrong, so it'll tell you exactly where problems are. Right now it just doesn't.

**Comment by forestasog** [comment]
ok lol, you were right.  actually i didn't even realize how many mistakes i had until you said.
sorry for being newb and thank you for help ^.^

so the last one i've stared at for like 4 hours and i have no idea what the problem is :c
http://pastebin.com/ZF5Hu7bJ

**Comment by Alan19** [comment]
You didn't close the curly braces for starter

**Comment by forestasog** [comment]
woooow xD thank you, yay i finished :D

**Comment by Greymerk** [comment]
I make JSON errors constantly when i write it. Embarrassingly it's incredibly difficult to figure out when something is wrong, because the mod tends to bury errors. I've been putting a lot of work into changing that so that the errors are intelligently explained.

Otherwise, even I find this stuff challenging, and I know exactly how it aught to be working.
