### ISSUE TITLE
Does not create structures (1.11.2)

### ISSUE THREAD

**Issue by 0Z3R0** [Greymerk/minecraft-roguelike#97]
Does not create structures of any type only makes holes (cubes obviously) very large in the ground (useful to find ores, but for nothing else)....

**Comment by Greymerk** [comment]
I've tested this using:
RoguelikeDungeons-1.11.2-1.6.3.jar
Forge 1.11.2 - 13.20.0.2252

Not seeing anything out of the ordinary. Maybe it's something else in your setup?
